const htsCards = [
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "Each time you roll to CHALLENGE, +2 to your roll.",
    card_effect_br:
      "Cada vez que você rolar para DESAFIAR. +2 para a sua rolada.",
    card_extra:
      "The effect is active when the challenge is initiated by the controlling player. Not all challenges",
    card_extra_br:
      "O efeito é ativado quando o desafio é iniciado pelo jogador que o controla. Não em todos os desafios",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 1,
    card_name: "The Fist of Reason",
    card_name_br: "O Punho da Razão",
    card_type: "Party Leader",
    card_type_br: "Líder de Grupo",
    card_class: "Fighter",
    card_class_br: "Lutador",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time you roll to use a Hero card's effect, +1 to your roll.",
    card_effect_br:
      "Cada vez que você rolar para usar um efeito de Carta de Heroi, +1 para a sua rolada.",
    card_extra: "",
    card_extra_br: "",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 2,
    card_name: "The Charismatic Song",
    card_name_br: "A Canção Carismática",
    card_type: "Party Leader",
    card_type_br: "Líder de Grupo",
    card_class: "Bard",
    card_class_br: "Bardo",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time you play a Modifier card on a roll, +1 or -1 to that roll.",
    card_effect_br:
      "Cada vez que você jogar um Modificador numa rolada, +1 ou -1 para essa rolada.",
    card_extra: "",
    card_extra_br: "",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 3,
    card_name: "The Protecting Horn",
    card_name_br: "O Chifre Protetor",
    card_type: "Party Leader",
    card_type_br: "Líder de Grupo",
    card_class: "Guardian",
    card_class_br: "Guardião",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time you roll to ATTACK a Monster card, +1 to your roll.",
    card_effect_br:
      "Cada vez que você rolar para ATACAR uma Carta de Monstro, +1 para a sua rolada.",
    card_extra: "",
    card_extra_br: "",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 4,
    card_name: "The Divine Arrow",
    card_name_br: "A Flecha Divina",
    card_type: "Party Leader",
    card_type_br: "Líder de Grupo",
    card_class: "Ranger",
    card_class_br: "Caçador",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Once per turn on your turn, you may spend an action point to pull a card from another player's hand.",
    card_effect_br:
      "Uma vez por turno no seu turno, você pode gastar um ponto de ação para pegar uma carta da mão de outro jogador.",
    card_extra: "This card cannot be used in a 2 player game.",
    card_extra_br: "Essa carta não pode ser usada em jogos de 2 jogadores.",
    card_expansion: false,
    card_id: 5,
    card_name: "The Shadow Claw",
    card_name_br: "A Garra Sombria",
    card_type: "Party Leader",
    card_type_br: "Líder de Grupo",
    card_class: "Thief",
    card_class_br: "Ladrão",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "Each time you play a Magic card, DRAW a card.",
    card_effect_br:
      "Cada vez que você jogar uma Carta Mágica, COMPRE uma carta.",
    card_expansion: false,
    card_id: 6,
    card_name: "The Cloaked Sage",
    card_name_br: "O Sábio Camuflado",
    card_type: "Party Leader",
    card_type_br: "Líder de Grupo",
    card_class: "Wizard",
    card_class_br: "Mago",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time another player plays a Modifier card on one of your rolls, +1 to your roll.",
    card_effect_br:
      "Cada vez que outro jogador jogar um Modificador em uma carta sua, +1 para a sua rolada.",
    card_expansion: false,
    card_id: 7,
    card_name: "Abyss Queen",
    card_name_br: "Rainha do Abismo",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "2 Any Heroes",
    card_requirements_br: "2 Heróis Quaisquer",
    slay_conditions_lose: "5- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "5- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "8+ SLAY this Monster Card",
    slay_conditions_win_br: "8+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time you successfully roll to use a Hero's effect, DRAW a card.",
    card_effect_br:
      "Cada vez que você rolar com sucesso para usar um efeito de Herói, COMPRE uma carta.",
    card_expansion: false,
    card_id: 8,
    card_name: "Artic Aries",
    card_name_br: "O Carneiro do Artico",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Any Hero",
    card_requirements_br: "1 Herói Qualquer",
    slay_conditions_lose: "6- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "6- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "10+ SLAY this Monster Card",
    slay_conditions_win_br: "10+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "Each time you roll, +1 to your roll.",
    card_effect_br: "Cada vez que você rolar, +1 para a sua rolada.",
    card_expansion: false,
    card_id: 9,
    card_name: "Anuran Cauldron",
    card_name_br: "Caldeirão Anuro",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "3 Any Heroes",
    card_requirements_br: "3 Heróis Quaisquer",
    slay_conditions_lose: "6- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "6- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "7+ SLAY this Monster Card",
    slay_conditions_win_br: "7+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time another player CHALLENGES you, that player must DISCARD a card.",
    card_effect_br:
      "Cada vez que outro jogador DESAFIAR você, aquele jogador deverá DESCARTAR uma carta.",
    card_expansion: false,
    card_id: 10,
    card_name: "Bloodwing",
    card_name_br: "Asa Sangrenta",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "2 Any Heroes",
    card_requirements_br: "2 HeróisQuaisquer",
    slay_conditions_lose: "6- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "6- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "9+ SLAY this Monster Card",
    slay_conditions_win_br: "9+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time another player plays a Modifier card on one of your rolls, +1 to your roll.",
    card_effect_br:
      "Cada vez que outro jogador jogar um Modificador em uma carta sua, +1 para a sua rolada.",
    card_expansion: false,
    card_id: 11,
    card_name: "Corrupted Sabretooth",
    card_name_br: "Dente-de-Sabre Corrompido",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "3 Any Heroes",
    card_requirements_br: "3 Heróis Quaisquer",
    slay_conditions_lose: "6- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "6- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "9+ SLAY this Monster Card and DRAW a card.",
    slay_conditions_win_br:
      "9+ DESTRUA essa Carta de Monstro e COMPRE uma carta.",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time any player (including you) plays a Modifier card, you may DRAW a card.",
    card_effect_br:
      "Cada vez que qualquer jogador (você inclusive)  jogar um Modificador, você pode COMPRAR uma carta.",
    card_expansion: false,
    card_id: 12,
    card_name: "Crowned Serpent",
    card_name_br: "Serpente Coroada",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "2 Any Heroes",
    card_requirements_br: "2 Heróis Quaisquer",
    slay_conditions_lose: "7- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "7- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "10+ SLAY this Monster Card",
    slay_conditions_win_br: "10+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time a Hero card in your Party is destroyed, you may DRAW a card.",
    card_effect_br:
      "Cada vez que uma Carta de Herói do seu grupo for destruído, você pode COMPRAR uma carta.",
    card_expansion: false,
    card_id: 13,
    card_name: "Dracos",
    card_name_br: "Dracos",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Any Hero",
    card_requirements_br: "1 Herói Qualquer",
    slay_conditions_win: "5- SLAY this Monster Card",
    slay_conditions_win_br: "5- DESTRUA essa Carta de Monstro",
    slay_conditions_lose: "8+ SACRIFICE a hero Card",
    slay_conditions_lose_br: "8+ SACRIFIQUE uma Carta de Herói.",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time you roll for a Hero card's effect, +1 to your roll.",
    card_effect_br:
      "Cada vez que você rolar para usar um efeito de carta de Herói, +1 para a sua rolada.",
    card_expansion: false,
    card_id: 14,
    card_name: "Dark Dragon King",
    card_name_br: "Rei Dragão Negro",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Bard + 1 Any",
    card_requirements_br: "1 Bardo + 1 Qualquer",
    slay_conditions_lose: "4- DISCARD 2 cards",
    slay_conditions_lose_br: "4- DESCARTE 2 cartas",
    slay_conditions_win: "8+ SLAY this Monster Card",
    slay_conditions_win_br: "8+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time you DRAW an item card, you may play it immediately.",
    card_effect_br:
      "Cada vez que você COMPRAR uma Carta de Item, você pode joga-la imediatamente.",
    card_expansion: false,
    card_id: 15,
    card_name: "Malamammoth",
    card_name_br: "Malamammoth",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Ranger + 1 Any",
    card_requirements_br: "1 Caçador + 1 Qualquer",
    slay_conditions_lose: "4- DISCARD 2 cards",
    slay_conditions_lose_br: "4- DESCARTE 2 cartas",
    slay_conditions_win: "8+ SLAY this Monster Card",
    slay_conditions_win_br: "8+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "You may spend an extra action point on each of your turns.",
    card_effect_br:
      "Você pode gastar um ponto de ação extra em cada um dos seus turnos.",
    card_expansion: false,
    card_id: 16,
    card_name: "Mega Slime",
    card_name_br: "Mega Slime",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "4 Any Heroes",
    card_requirements_br: "4 Heróis Quaisquer",
    slay_conditions_lose: "7- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "7- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "8+ SLAY this Monster Card & DRAW 2 cards",
    slay_conditions_win_br:
      "8+ DESTRUA essa Carta de Monstro & COMPRE 2 cartas.",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time you DRAW a Magic card, you may play it immediately.",
    card_effect_br:
      "Cada vez que você COMPRAR uma Carta Mágica, você pode joga-la imediatamente.",
    card_expansion: false,
    card_id: 17,
    card_name: "Orthus",
    card_name_br: "Orthus",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Wizard + 1 Any",
    card_requirements_br: "1 Mago + 1 Qualquer",
    slay_conditions_lose: "4- DISCARD 2 cards",
    slay_conditions_lose_br: "4- DESCARTE 2 cartas.",
    slay_conditions_win: "8+ SLAY this Monster Card",
    slay_conditions_win_br: "8+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time you DRAW a Modifier card, you may reveal it and DRAW a second card.",
    card_effect_br:
      "Cada vez que você COMPRAR um Modificador, você pode revela-lo e COMPRAR uma segunda carta.",
    card_expansion: false,
    card_id: 18,
    card_name: "Rex Major",
    card_name_br: "Grande Rex",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Guardian + 1 Any",
    card_requirements_br: "1 Guardião + 1 Qualquer",
    slay_conditions_lose: "4- DISCARD 2 cards",
    slay_conditions_lose_br: "4- DESCARTE 2 cartas",
    slay_conditions_win: "8+ SLAY this Monster Card",
    slay_conditions_win_br: "8+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "Your Hero cards cannot be destroyed.",
    card_effect_br: "Suas Cartas de Herói não podem ser destruidas.",
    card_expansion: false,
    card_id: 19,
    card_name: "Terratuga",
    card_name_br: "Terratuga",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Any Hero",
    card_requirements_br: "1 Herói Qualquer",
    slay_conditions_lose: "7- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "7- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "11+ SLAY this Monster Card",
    slay_conditions_win_br: "11+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "Each time you roll for a Challenge card, +1 to your roll.",
    card_effect_br:
      "Cada vez que você rolar para uma Carta de Desafio, +1 para a sua rolada.",
    card_expansion: false,
    card_id: 20,
    card_name: "Titan Wyvern",
    card_name_br: "Wyvern Titã",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Fighter + 1 Any",
    card_requirements_br: "1 Lutador + 1 Qualquer",
    slay_conditions_lose: "4- DISCARD 2 cards",
    slay_conditions_lose_br: "4- DESCARTE 2 cartas",
    slay_conditions_win: "8+ SLAY this Monster Card",
    slay_conditions_win_br: "8+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "Item cards you play cannot be challenged.",
    card_effect_br: "Cartas de Item que você jogar não podem ser desafiadas.",
    card_expansion: false,
    card_id: 21,
    card_name: "Warworn Owlbear",
    card_name_br: "Urso-Coruja Marcado pela Guerra",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Thief + 1 Any",
    card_requirements_br: "1 Ladrão + 1 Qualquer",
    slay_conditions_lose: "4- DISCARD 2 cards",
    slay_conditions_lose_br: "4- DESCARTE 2 cartas",
    slay_conditions_win: "8+ SLAY this Monster Card",
    slay_conditions_win_br: "8+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "8+ DESTROY a Hero card.",
    card_effect_br: "8+ DESTRUA uma Carta de Herói.",
    card_expansion: false,
    card_id: 22,
    card_name: "Bad Axe",
    card_name_br: "Machado Ruim",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Fighter",
    card_class_br: "Lutador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "7+ Pull a card from another player's hand. If it is a Hero card, pull a second card from that player's hand.",
    card_effect_br:
      "7+ Pegue uma carta da mão de outro jogador. se for uma Carta de Herói, pegue uma segunda carta da mão deste mesmo jogador.",
    card_expansion: false,
    card_id: 23,
    card_name: "Bear Claw",
    card_name_br: "Garra de Urso",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Fighter",
    card_class_br: "Lutador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "7+ Each other player must DISCARD a card. Choose one of the discarded cards and add it to your hand.",
    card_effect_br:
      "7+ Cada outro jogador deve DESCARTAR uma carta. Escolha uma das cartas descartadas desta maneira e coloque na sua mão.",
    card_expansion: false,
    card_id: 24,
    card_name: "Beary Wise",
    card_name_br: "Barburso Sábio",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Fighter",
    card_class_br: "Lutador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "5+ Pull a card from another player's hand. If it is a Challenge card, pull a second card from that player's hand.",
    card_effect_br:
      "5+ Pegue uma carta da mão de outro jogador. Se for uma Carta de DESAFIO, pegue uma segunda carta da mão deste mesmo jogador.",
    card_expansion: false,
    card_id: 25,
    card_name: "Fury Knuckle",
    card_name_br: "Articulações Furiosas",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Fighter",
    card_class_br: "Lutador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "5+ Choose a player. That player must DISCARD 2 cards.",
    card_effect_br:
      "5+ Escolha um jogador. Este jogador deve DESCARTAR 2 cartas.",
    card_expansion: false,
    card_id: 26,
    card_name: "Heavy Bear",
    card_name_br: "Urso Pesado",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Fighter",
    card_class_br: "Lutador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "8+ DRAW 2 cards. If at least one of those cards is a Challenge card, you may reveal it, then DESTROY a Hero card.",
    card_effect_br:
      "8+ COMPRE 2 cartas. Se pelo menos uma delas for uma carta de DESAFIO, você pode revela-la e DESTRUIR uma Carta de Herói.",
    card_expansion: false,
    card_id: 27,
    card_name: "Pan Chucks",
    card_name_br: "Panda Nunchaku",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Fighter",
    card_class_br: "Lutador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "10+ DISCARD up to 3 cards. For each card discarded, DESTROY a Hero card.",
    card_effect_br:
      "10+ DESCARTE até 3 cartas. Para cada carta descartada, DESTRUA uma Carta de Herói.",
    card_expansion: false,
    card_id: 28,
    card_name: "Qi Bear",
    card_name_br: "Urso do Qi",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Fighter",
    card_class_br: "Lutador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "4+ Each other player with a Fighter in their Party must DISCARD a card.",
    card_effect_br:
      "4+ Cada outro jogador com um Lutador em sem grupo deve DESCARTAR uma carta.",
    card_expansion: false,
    card_id: 29,
    card_name: "Tough Teddy",
    card_name_br: "Ursinho Brigão",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Fighter",
    card_class_br: "Lutador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "9+ Trade hands with another player.",
    card_effect_br: "9+ Troque de mão com outro jogador.",
    card_expansion: false,
    card_id: 30,
    card_name: "Dodgy Dealer",
    card_name_br: "Negociante Duvidoso",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Bard",
    card_class_br: "Bardo",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "8+ DRAW a card and play a Hero card from your hand immediately.",
    card_effect_br:
      "8+ COMPRE uma carta e jogue uma Carta de Herói da sua mão imediatamente.",
    card_expansion: false,
    card_id: 31,
    card_name: "Fuzzy Cheeks",
    card_name_br: "Bochechas Peludas",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Bard",
    card_class_br: "Bardo",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "8+ Each other player must give you a card from their hand.",
    card_effect_br:
      "8+ Cada outro jogador deve te dar uma carta da própria mão.",
    card_expansion: false,
    card_id: 32,
    card_name: "Greedy Cheeks",
    card_name_br: "Bochechas Gananciosas",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Bard",
    card_class_br: "Bardo",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "7+ Pull a card from another player's hand. If that card is a Hero card, you may play it immediately",
    card_effect_br:
      "7+ Pegue uma carta da mão de outro jogador. Se essa carta for uma Carta de Herói, você pode joga-la imediatamente.",
    card_expansion: false,
    card_id: 33,
    card_name: "Lucky Bucky",
    card_name_br: "Bucky Sortuda",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Bard",
    card_class_br: "Bardo",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "7+ DRAW a card. If that card is a Hero card, you may play it immediately.",
    card_effect_br:
      "7+ COMPRE uma carta. Se essa carta for uma Carta de Herói, você pode joga-la imediamente.",
    card_expansion: false,
    card_id: 34,
    card_name: "Mellow Dee",
    card_name_br: "Soneto",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Bard",
    card_class_br: "Bardo",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "2+ Do nothing.",
    card_effect_br: "2+ Não faça nada.",
    card_expansion: false,
    card_id: 35,
    card_name: "Napping Nibbles",
    card_name_br: "Cochilo Mordiscante",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Bard",
    card_class_br: "Bardo",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "7+ DRAW 2 cards.",
    card_effect_br: "7+ COMPRE 2 cartas.",
    card_expansion: false,
    card_id: 36,
    card_name: "Peanut",
    card_name_br: "Amendoim",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Bard",
    card_class_br: "Bardo",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "6+ Choose a player. STEAL a Hero card from that player's Party and move Tipsy Tootie to that player's Party.",
    card_effect_br:
      "6+ Escolha outro jogador. ROUBE uma Carta de Herói do grupo deste jogador e mova Dentinhos Embriagados para o grupo deste jogador.",
    card_expansion: false,
    card_id: 37,
    card_name: "Tipsy Tootie",
    card_name_br: "Dentinhos Embriagados",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Bard",
    card_class_br: "Bardo",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "9+ Hero cards in your Party cannot be stolen until your next turn.",
    card_effect_br:
      "9+ Cartas de Herói no seu grupo não podem ser roubadas até o seu próximo turno.",
    card_expansion: false,
    card_id: 38,
    card_name: "Calming Voice",
    card_name_br: "Voz Calmante",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Guardian",
    card_class_br: "Guardião",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "7+ Search the discard pile for a Hero card and add it to your hand.",
    card_effect_br:
      "7+ Procure na pilha de descarte por uma Carta de Herói e adicione-a à sua mão.",
    card_expansion: false,
    card_id: 39,
    card_name: "Guiding Light",
    card_name_br: "Luz Guiadora",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Guardian",
    card_class_br: "Guardião",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "5+ Return a Cursed Item card equipped to a Hero card in your Party to your hand.",
    card_effect_br:
      "5+ Retorne uma Carta de Item Amaldiçoado equipado em um Herói do seu grupo para a sua mão.",
    card_expansion: false,
    card_id: 40,
    card_name: "Holy Curselifter",
    card_name_br: "Quebrador de Maldição Sagrado",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Guardian",
    card_class_br: "Guardião",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "8+ Cards you play cannot be challenged for the rest of your turn.",
    card_effect_br:
      "8+ Cartas que você jogar não podem ser desafiadas pelo resto do seu turno.",
    card_expansion: false,
    card_id: 41,
    card_name: "Iron Resolve",
    card_name_br: "Determinação de Ferro",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Guardian",
    card_class_br: "Guardião",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "8+ Hero cards in your Party cannot be destroyed until your next turn.",
    card_effect_br:
      "8+ Cartas de Herói no seu Grupo não podem ser destruidas até o seu próximo turno.",
    card_expansion: false,
    card_id: 42,
    card_name: "Mighty Blade",
    card_name_br: "Lâmina Poderosa",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Guardian",
    card_class_br: "Guardião",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "6+ Search the discard pile for a Modifier card and add it to your hand.",
    card_effect_br:
      "6+ Procure na pilha de descarte por uma Carta de Modificador e a coloque-a na sua mão.",
    card_expansion: false,
    card_id: 43,
    card_name: "Radiant Horn",
    card_name_br: "Chifre Radiante",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Guardian",
    card_class_br: "Guardião",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "9+ +5 to all your rolls until the end of your turn.",
    card_effect_br:
      "9+ +5 para todas as suas roladas até o final do seu turno.",
    card_expansion: false,
    card_id: 44,
    card_name: "Vibrant Glow",
    card_name_br: "Brilho Vibrante",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Guardian",
    card_class_br: "Guardião",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "6+ +3 to all your rolls until the end of your turn.",
    card_effect_br:
      "6+ +3 para todas as suas roladas até o final do seu turno.",
    card_expansion: false,
    card_id: 45,
    card_name: "Wise Shield",
    card_name_br: "Escudo Sábio",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Guardian",
    card_class_br: "Guardião",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "7+ Look at the top 3 cards of the deck. Add one to your hand, then return the other two to the top of the deck in any order.",
    card_effect_br:
      "7+ Olhe as 3 primeiras cartas do baralho. Adicione uma à sua mão e retorne as outras duas para o topo do baralho em qualquer ordem.",
    card_expansion: false,
    card_id: 46,
    card_name: "Bullseye",
    card_name_br: "Olho Afiado",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Ranger",
    card_class_br: "Caçador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "6+ Play an item card from your hand immediately and DRAW a card.",
    card_effect_br:
      "6+ Jogue uma carta de item da sua mão imediatamente a COMPRE uma carta.",
    card_expansion: false,
    card_id: 47,
    card_name: "Hook",
    card_name_br: "Gancho",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Ranger",
    card_class_br: "Caçador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "5+ Search the discard pile for an item card and add it to your hand.",
    card_effect_br:
      "5+ Procure na pilha de descarte por uma carta de item e adicione à sua mão",
    card_expansion: false,
    card_id: 48,
    card_name: "Lookie Rookie",
    card_name_br: "Olheiro Novato",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Ranger",
    card_class_br: "Caçador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "8+ DRAW 2 cards. If at least one of those cards is an item card, you may play one of them immediately.",
    card_effect_br:
      "8+ COMPRE 2 cartas. Se pelo menos uma delas for uma carta de item, voce pode jogar uma delas imediatamente.",
    card_expansion: false,
    card_id: 49,
    card_name: "Quick Draw",
    card_name_br: "Sacada Rápida",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Ranger",
    card_class_br: "Caçador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "9+ DESTROY a Hero and DRAW a card.",
    card_effect_br: "9+ DESTRUA um Herói e COMPRE uma carta.",
    card_expansion: false,
    card_id: 50,
    card_name: "Serious Grey",
    card_name_br: "Sirius Grey",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Ranger",
    card_class_br: "Caçador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "5+ Look at another player's hand.",
    card_effect_br: "5+ Olhe a mão de outro jogador.",
    card_expansion: false,
    card_id: 51,
    card_name: "Sharp Fox",
    card_name_br: "Raposa Afiada",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Ranger",
    card_class_br: "Caçador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "8+ DRAW 3 cards and DISCARD a card.",
    card_effect_br: "8+ COMPRE 3 cartas e DESCARTE uma carta.",
    card_expansion: false,
    card_id: 52,
    card_name: "Wildshot",
    card_name_br: "Tiro Selvagem",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Ranger",
    card_class_br: "Caçador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "10+ DRAW cards until you have 7 cards in your hand.",
    card_effect_br: "10+ COMPRE cartas até ter 7 cartas na sua mão.",
    card_expansion: false,
    card_id: 53,
    card_name: "Wily Red",
    card_name_br: "Dentes Raivosos",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Ranger",
    card_class_br: "Caçador",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "9+ STEAL a Hero card.",
    card_effect_br: "9+ ROUBE uma carta de Herói.",
    card_expansion: false,
    card_id: 54,
    card_name: "Kit Napper",
    card_name_br: "Sequestrador",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Thief",
    card_class_br: "Ladrão",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "10+ Choose a player. STEAL a Hero from that player and pull a card from that player's hand.",
    card_effect_br:
      "10+ Escolha um jogador. ROUBE um Herói deste jogador e pegue uma carta da mão deste mesmo jogador.",
    card_expansion: false,
    card_id: 55,
    card_name: "Meowzio",
    card_name_br: "Miauzio",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Thief",
    card_class_br: "Ladrão",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "6+ Pull 2 cards from another player's hand. That player may DRAW a card.",
    card_effect_br:
      "6+ Pegue 2 cartas da mão de outro jogador. Esse jogador pode COMPRAR uma carta.",
    card_expansion: false,
    card_id: 56,
    card_name: "Plundering Puma",
    card_name_br: "Puma Saqueador",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Thief",
    card_class_br: "Ladrão",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "9+ DESTROY a Hero card. If that Hero card had an item card equipped to it, add that item card to your hand instead of moving it to the discard pile.",
    card_effect_br:
      "9+ DESTRUA uma Carta de Herói. Se essa Carta de Herói tem um item equipado nela, adicione esta Carta de Item à sua mão no lugar de coloca-la na pilha de descarte.",
    card_expansion: false,
    card_id: 57,
    card_name: "Shurikitty",
    card_name_br: "Shurigata",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Thief",
    card_class_br: "Ladrão",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "8+ Look at another player's hand. Choose a card and add it to your hand.",
    card_effect_br:
      "8+ Olhe a mão de outro jogador. Escolha uma carta e adicione-a à sua mão.",
    card_expansion: false,
    card_id: 58,
    card_name: "Silent Shadow",
    card_name_br: "Sombra Silenciosa",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Thief",
    card_class_br: "Ladrão",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "6+ Pull 2 cards from another player's hand, then DISCARD one of those cards.",
    card_effect_br:
      "6+ Pegue 2 cartas da mão de outro jogador e depois DESCARTE uma dessas cartas.",
    card_expansion: false,
    card_id: 59,
    card_name: "Slippery Paws",
    card_name_br: "Patas Escorregadias",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Thief",
    card_class_br: "Ladrão",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "6+ Pull a card from another player's hand. If that card is an item card, you may play it immediately.",
    card_effect_br:
      "6+ Pegue uma carta da mão de outro jogador. Se esta carta for uma Carta de Item, você pode joga-la imediatamente.",
    card_expansion: false,
    card_id: 60,
    card_name: "Sly Pickings",
    card_name_br: "Escolhas Astutas",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Thief",
    card_class_br: "Ladrão",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "7+ Pull a card from the hand of each other player with a Thief in their Party.",
    card_effect_br:
      "7+ Pegue uma carta da mão de cada outro jogador com um Ladrão no seu Grupo.",
    card_expansion: false,
    card_id: 61,
    card_name: "Smooth Mimimeow",
    card_name_br: "Ladrão Felpudo",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Thief",
    card_class_br: "Ladrão",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "5+ Search the discard pile for a Magic card and add it to your hand.",
    card_effect_br:
      "5+ Procure na pilha de descarte por uma Carta Mágica e adicione-a à sua mão.",
    card_expansion: false,
    card_id: 62,
    card_name: "Bun Bun",
    card_name_br: "Coelhinho",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Wizard",
    card_class_br: "Mago",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "6+ Pull a card from another player's hand. If it is a Magic card, you may play it immediately.",
    card_effect_br:
      "6+ Pegue uma carta da mão de outro jogador. Se for uma Carta Mágica, voc&e pode joga-la imediatamente.",
    card_expansion: false,
    card_id: 63,
    card_name: "Buttons",
    card_name_br: "Botões",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Wizard",
    card_class_br: "Mago",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "10+ DESTROY 2 Hero cards",
    card_effect_br: "10+ DESTRUA 2 Cartas de Herói.",
    card_expansion: false,
    card_id: 64,
    card_name: "Fluffy",
    card_name_br: "Fofinho",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Wizard",
    card_class_br: "Mago",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "7+ Choose a player. That player must SACRIFICE a Hero card.",
    card_effect_br:
      "7+ Escolha um jogador. Esse jogador deve SACRIFICAR uma Carta de Herói.",
    card_expansion: false,
    card_id: 65,
    card_name: "Hopper",
    card_name_br: "Saltador",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Wizard",
    card_class_br: "Mago",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "6+ DRAW a card. If it is a Magic card, you may play it immediately and DRAW a second card.",
    card_effect_br:
      "6+ COMPRE uma carta. Se for uma Carta Mágica, você pode joga-la imadiatamente e COMPRAR uma segunda carta.",
    card_expansion: false,
    card_id: 66,
    card_name: "Snowball",
    card_name_br: "Bola de Neve",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Wizard",
    card_class_br: "Mago",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "10+ Each other player must SACRIFICE a Hero card.",
    card_effect_br:
      "10+ Cada outro jogador deve SACRIFICAR uma Carta de Herói.",
    card_expansion: false,
    card_id: 67,
    card_name: "Spooky",
    card_name_br: "Assustador",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Wizard",
    card_class_br: "Mago",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "11+ STEAL a Hero card and DESTROY a Hero card.",
    card_effect_br:
      "11+ ROUBE uma Carta de Herói e DESTRUA uma Carta de Herói.",
    card_expansion: false,
    card_id: 68,
    card_name: "Whiskers",
    card_name_br: "Bigodes",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Wizard",
    card_class_br: "Mago",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "10+ STEAL a Hero and roll to use its effect immediately",
    card_effect_br:
      "10+ ROUBE um Herói e role para usar seu efeito imediatamente.",
    card_expansion: false,
    card_id: 69,
    card_name: "Wiggles",
    card_name_br: "Zigue Zague",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Wizard",
    card_class_br: "Mago",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "The equipped Hero card is considered a Bard instead of its original class.",
    card_effect_br:
      "A Carta de Herói equipada é considerada um Bardo ao invés da sua classe original. ",
    card_expansion: false,
    card_id: 70,
    card_name: "Bard Mask",
    card_name_br: "Máscara do Bardo",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "The equipped Hero card is considered a Fighter instead of its original class.",
    card_effect_br:
      "A Carta de Herói equipada é considerada um Lutador ao invés da sua classe original.",
    card_expansion: false,
    card_id: 71,
    card_name: "Fighter Mask",
    card_name_br: "Máscara do Lutador",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "The equipped Hero card is considered a Guardian instead of its original class.",
    card_effect_br:
      "A Carta de Herói equipada é considerada um Guardião ao invés da sua classe original.",
    card_expansion: false,
    card_id: 72,
    card_name: "Guardian Mask",
    card_name_br: "Máscara do Guardião",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "The equipped Hero card is considered a Ranger instead of its original class.",
    card_effect_br:
      "A Carta de Herói equipada é considerada um Caçador ao invés da sua classe original.",
    card_expansion: false,
    card_id: 73,
    card_name: "Ranger Mask",
    card_name_br: "Máscara do Caçador",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "The equipped Hero card is considered a Thief instead of its original class.",
    card_effect_br:
      "A Carta de Herói equipada é considerada um Ladrão ao invés da sua classe original.",
    card_expansion: false,
    card_id: 74,
    card_name: "Thief Mask",
    card_name_br: "Máscara do Ladrão",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "The equipped Hero card is considered a Wizard instead of its original class.",
    card_effect_br:
      "A Carta de Herói equipada é considerada um Mago ao invés da sua classe original.",
    card_expansion: false,
    card_id: 75,
    card_name: "Wizard Mask",
    card_name_br: "Máscara do Mago",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "If the equipped Hero card would be sacrificed or destroyed, move Decoy Doll to the discard pile instead.",
    card_effect_br:
      "Se a Carta de Herói equipada fosse ser sacrificada ou destruída, mova Boneca Isca para a pilha de descarte em seu lugar.",
    card_expansion: false,
    card_id: 76,
    card_name: "Decoy Doll",
    card_name_br: "Boneca Isca",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "If you unsuccessfully roll to use the equipped Hero card's effect, DRAW a card.",
    card_effect_br:
      "Se você rolar sem sucesso para usar o efeito da Carta de Herói equipada, COMPRE uma carta.",
    card_expansion: false,
    card_id: 77,
    card_name: "Particularly Rusty Coin",
    card_name_br: "Moeda Particularmente Enferrujada",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time you roll to use the equipped Hero card's effect, +2 to your roll.",
    card_effect_br:
      "Cada vez que você rolar para usar o efeito da Carta de Herói equipada, +2 para a sua rolada.",
    card_expansion: false,
    card_id: 78,
    card_name: "Really Big Ring",
    card_name_br: "Anel Realmente Grande",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Each time you roll to use the equipped Hero card's effect, -2 to your roll.",
    card_effect_br:
      "Cada vez que você rolar para usar o efeito da Carta de Herói equipada, -2 para a sua rolada.",
    card_expansion: false,
    card_id: 79,
    card_name: "Curse of the Snake's Eyes",
    card_name_br: "Mardição do Olho da Serpente",
    card_type: "Cursed Items",
    card_type_br: "Items Amaldiçoados",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "You cannot use the equipped Hero card's effect.",
    card_effect_br: "Você não pode usar o efeito da Carta de Herói equipada.",
    card_expansion: false,
    card_id: 80,
    card_name: "Sealing Key",
    card_name_br: "Chave Selante",
    card_type: "Cursed Items",
    card_type_br: "Items Amaldiçoados",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "If you successfully roll to use the equipped Hero card's effect, DISCARD a card.",
    card_effect_br:
      "Se você rolar com sucesso para usar o efeito da Carta de Herói equipada, DESCARTE uma carta.",
    card_expansion: false,
    card_id: 81,
    card_name: "Suspiciously Shiny Coin",
    card_name_br: "Moeda Brilhante Suspeita",
    card_type: "Cursed Items",
    card_type_br: "Items Amaldiçoados",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Play this card after any player (including you) rolls the dice. +1 or -3 to that roll.",
    card_effect_br:
      "Jogue esta carta depois de qualquer jogador (incluindo você) rolar o dado. +1 ou -3 para essa rolada.",
    card_expansion: false,
    card_id: 82,
    card_name: "Modifier +1/-3",
    card_name_br: "Modificador +1/-3",
    card_type: "Modifier Card",
    card_type_br: "Carta de Modificador",
    game: "Here To Slay",
    card_class: "Modifiers",
    card_class_br: "Modificadores",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Play this card after any player (including you) rolls the dice. +2 or -2 to that roll.",
    card_effect_br:
      "Jogue esta carta depois de qualquer jogador (incluindo você) rolar o dado. +2 ou -2 para essa rolada.",
    card_expansion: false,
    card_id: 83,
    card_name: "Modifier +2/-2",
    card_name_br: "Modificador +2/-2",
    card_type: "Modifier Card",
    card_type_br: "Carta de Modificador",
    game: "Here To Slay",
    card_class: "Modifiers",
    card_class_br: "Modificadores",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Play this card after any player (including you) rolls the dice. +3 or -1 to that roll.",
    card_effect_br:
      "Jogue esta carta depois de qualquer jogador (incluindo você) rolar o dado. +3 ou -1 para essa rolada.",
    card_expansion: false,
    card_id: 84,
    card_name: "Modifier +3/-1",
    card_name_br: "Modificador +3/-1",
    card_type: "Modifier Card",
    card_type_br: "Carta de Modificador",
    game: "Here To Slay",
    card_class: "Modifiers",
    card_class_br: "Modificadores",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Play this card after any player (including you) rolls the dice. +4 to that roll.",
    card_effect_br:
      "Jogue esta carta depois de qualquer jogador (incluindo você) rolar o dado. +4 para essa rolada.",
    card_expansion: false,
    card_id: 85,
    card_name: "Modifier +4",
    card_name_br: "Modificador +4",
    card_type: "Modifier Card",
    card_type_br: "Carta de Modificador",
    game: "Here To Slay",
    card_class: "Modifiers",
    card_class_br: "Modificadores",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Play this card after any player (including you) rolls the dice. -4 to that roll.",
    card_effect_br:
      "Jogue esta carta depois de qualquer jogador (incluindo você) rolar o dado. -4 para essa rolada.",
    card_expansion: false,
    card_id: 86,
    card_name: "Modifier -4",
    card_name_br: "Modificador -4",
    card_type: "Modifier Card",
    card_type_br: "Carta de Modificador",
    game: "Here To Slay",
    card_class: "Modifiers",
    card_class_br: "Modificadores",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Search the discard pile for a Hero card and add it to your hand.",
    card_effect_br:
      "Procure na pilha de descarte por uma Carta de Herói e adicione-a à sua mão.",
    card_expansion: false,
    card_id: 87,
    card_name: "Call to the Fallen",
    card_name_br: "Chamado aos Caídos",
    card_type: "Magic Card",
    card_type_br: "Carta Mágica",
    game: "Here To Slay",
    card_class: "Magic",
    card_class_br: "Mágica",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "DRAW 3 cards and DISCARD a card.",
    card_effect_br: "COMPRE 3 cartas e DESCARTE uma carta.",
    card_expansion: false,
    card_id: 88,
    card_name: "Critical Boost",
    card_name_br: "Impulso Crítico",
    card_type: "Magic Card",
    card_type_br: "Carta Mágica",
    game: "Here To Slay",
    card_class: "Magic",
    card_class_br: "Mágica",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "DISCARD a card, then DESTROY a Hero card.",
    card_effect_br: "DESCARTE uma carta, depois DESTRUA uma Carta de Herói.",
    card_expansion: false,
    card_id: 89,
    card_name: "Destructive Spell",
    card_name_br: "Feitiço Destrutivo",
    card_type: "Magic Card",
    card_type_br: "Carta Mágica",
    game: "Here To Slay",
    card_class: "Magic",
    card_class_br: "Mágica",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "+2 to all of your rolls until the end of your turn.",
    card_effect_br: "+2 para todas as suas roladas até o fim do seu turno.",
    card_expansion: false,
    card_id: 90,
    card_name: "Enchanted Spell",
    card_name_br: "Feitiço Encantado",
    card_type: "Magic Card",
    card_type_br: "Carta Mágica",
    game: "Here To Slay",
    card_class: "Magic",
    card_class_br: "Mágica",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "DISCARD 2 cards, then STEAL a Hero card.",
    card_effect_br: "DESCARTE 2 cartas, depois ROUBE uma Carta de Herói.",
    card_expansion: false,
    card_id: 91,
    card_name: "Entangling Trap",
    card_name_br: "Armadilha Emaranhada",
    card_type: "Magic Card",
    card_type_br: "Carta Mágica",
    game: "Here To Slay",
    card_class: "Magic",
    card_class_br: "Mágica",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Choose a player. STEAL a Hero card from that player's Party, then move a Hero card from your Party to that player's Party.",
    card_effect_br:
      "Escolha um jogador. ROUBE uma Carta de Herói do Grupo deste jogador e depois mova uma Carta de Herói do seu Grupo para o Grupo do jogador.",
    card_expansion: false,
    card_id: 92,
    card_name: "Forced Exchange",
    card_name_br: "Troca Forçada",
    card_type: "Magic Card",
    card_type_br: "Carta Mágica",
    game: "Here To Slay",
    card_class: "Magic",
    card_class_br: "Mágica",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Return every equipped item card to its respective player's hand.",
    card_effect_br:
      "Retorne cada item equipada para a mão do seu respectivo jogador.",
    card_expansion: false,
    card_id: 93,
    card_name: "Forceful Winds",
    card_name_br: "Ventos Fortes",
    card_type: "Magic Card",
    card_type_br: "Carta Mágica",
    game: "Here To Slay",
    card_class: "Magic",
    card_class_br: "Mágica",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Return an Item card equipped to any player's Hero card to that player's hand, then DRAW a card.",
    card_effect_br:
      "Retorne um Item equipado em qualquer Herói de qualquer jogador para a mão daquele jogador, depois COMPRE uma carta.",
    card_expansion: false,
    card_id: 94,
    card_name: "Winds of Change",
    card_name_br: "Ventos da Mudança",
    card_type: "Magic Card",
    card_type_br: "Carta Mágica",
    game: "Here To Slay",
    card_class: "Magic",
    card_class_br: "Mágica",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "You may play this card when another player attempts to play a Hero, Item, or Magic card. CHALLENGE that card.",
    card_effect_br:
      "Você pode jogar esta carta quando outro jogador tentar jogar uma carta de Herói, Item ou Mágica. DESAFIE aquela carta.",
    card_expansion: false,
    card_id: 95,
    card_name: "Challenge Card",
    card_name_br: "Desafio",
    card_type: "Challenge Card",
    card_type_br: "Carta de Desafio",
    game: "Here To Slay",
    card_class: "Challenge",
    card_class_br: "Desafio",
    card_extra:
      "You can only challenge a card being played not an effect; You cannot challenge modifiers or other challenge cards.; Any player that plays a hero, item or magic card MUST give other players the opportunity to respond before continuing.",
    card_extra_br:
      "Você só pode desafiar uma carta sendo jogada, não um efeito; Você não pode desafiar modificadores ou outras cartas de desafio; Qualquer jogador que jogue um Herói, Item ou mágica, DEVE dar aos outros jogadores a oportunidade de resposta antes de continuar. ",
  },

  // ========================================================================================================================
  // WARRIOR AND DRUIDS EXPANSION
  // ========================================================================================================================

  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "Once per turn on each player's turn, you may choose any player's roll. -1 to that roll.",
    card_effect_br:
      "Uma vez por turno, no turno de cada jogador, você pode escolher qualquer rolada de qualquer jogador. -1 para aquela rolada.",
    card_expansion: true,
    card_id: 96,
    card_name: "The Noble Shaman",
    card_name_br: "O Xamã Nobre",
    card_type: "Party Leader",
    card_type_br: "Líder de Grupo",
    card_class: "Druid",
    card_class_br: "Druida",
    game: "Here To Slay",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "Each time you roll, +1 to your roll for each Item card equipped to a Hero card in your Party.",
    card_effect_br:
      "Cada vez que você rolar os dados, +1 para a sua rolada para cada Carta de Item equipada em uma Carta de Herói no seu Grupo.",
    card_expansion: true,
    card_id: 97,
    card_name: "The Piercing Howl",
    card_name_br: "O Uivo Perfurante",
    card_type: "Party Leader",
    card_type_br: "Líder de Grupo",
    card_class: "Warrior",
    card_class_br: "Guerreiro",
    game: "Here To Slay",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect: "Each time any player sacrifices a card, DRAW a card.",
    card_effect_br:
      "Cada vez que qualquer jogador sacrificar uma carta, COMPRE uma carta.",
    card_expansion: true,
    card_id: 98,
    card_name: "Feral Dragon",
    card_name_br: "Dragão Feroz",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "2 Any Heroes",
    card_requirements_br: "2 Heróis Quaisquer",
    slay_conditions_lose: "6- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "6- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "9+ SLAY this Monster Card",
    slay_conditions_win_br: "9+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "Once per turn on your turn, you may DRAW a card without spending an action point.",
    card_effect_br:
      "Uma vez por turno no seu turno, você pode COMPRAR uma carta sem gastar um ponto de ação.",
    card_expansion: true,
    card_id: 99,
    card_name: "Muscipula Rex",
    card_name_br: "Muscipula Rex",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "3 Any Heroes",
    card_requirements_br: "3 Heróis Quaisquer",
    slay_conditions_lose: "7- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "7- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "10+ SLAY this Monster Card",
    slay_conditions_win_br: "10+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "8- ATTACK a Monster card immediately. (You must still meet its Party requirement.)",
    card_effect_br:
      "8- ATAQUE uma Carta de Monstro imediatamente. (Você ainda deve atender ao requisito de Grupo para atacar.) ",
    card_expansion: true,
    card_id: 100,
    card_name: "Big Buckley",
    card_name_br: "Grande Fivela",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Druid",
    card_class_br: "Druida",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "6- Look at another player's hand. Choose a Hero card from their hand (if they have one) and bring it into your Party.",
    card_effect_br:
      "6- Olhe a mão de outro jogador. Escolha uma Carta de Herói da mão deste jogador (se ele tiver uma) e coloque-a no seu Grupo.",
    card_expansion: true,
    card_id: 101,
    card_name: "Buck Omens",
    card_name_br: "O Bode do Presságio",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Druid",
    card_class_br: "Druida",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "7- SACRIFICE a Hero card, then DRAW cards until you have 7 cards in your hand.",
    card_effect_br:
      "7- SACRIFIQUE uma Carta de Herói, depois COMPRE cartas até que você tenha 7 cartas na sua mão.",
    card_expansion: true,
    card_id: 102,
    card_name: "Doe Fallow",
    card_name_br: "Corça do Pousio",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Druid",
    card_class_br: "Druida",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect: "7- You may play up to 2 Magic cards immediately.",
    card_effect_br: "7- Você pode jogar até 2 Cartas Mágicas imediatamente.",
    card_expansion: true,
    card_id: 103,
    card_name: "Glowing Antler",
    card_name_br: "Chifre Brilhante",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Druid",
    card_class_br: "Druida",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "7- SACRIFICE a Hero card. +5 or -5 to each of your rolls until your next turn.",
    card_effect_br:
      "7- SACRIFIQUE uma Carta de Herói. +5 ou -5 para cada uma das suas roladas até o fim do seu próximo turno.",
    card_expansion: true,
    card_id: 104,
    card_name: "Majestelk",
    card_name_br: "Majestalce",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Druid",
    card_class_br: "Druida",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "5- Search the discard pile for a Hero card and add it to your hand, then play it immediately",
    card_effect_br:
      "5- Procure na pila de descarte por uma Carta de Herói e adicione-a na sua mão, depois jogue-a imediatamente.",
    card_expansion: true,
    card_id: 105,
    card_name: "Magus Moose",
    card_name_br: "Alce Mágico",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Druid",
    card_class_br: "Druida",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "7- Until your next turn, if a Hero card in your Party would be sacrificed or destroyed, return it to your hand instead.",
    card_effect_br:
      "7- Até o seu próximo turno, se uma Carta de Herói do seu Grupo for ser sacrificada ou destruída, retorne-a para sua mão.",
    card_expansion: true,
    card_id: 106,
    card_name: "Maegisty",
    card_name_br: "Mãejestade",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Druid",
    card_class_br: "Druida",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "8- No other player can play Modifier cards until the end of your turn.",
    card_effect_br:
      "8- Nenhum outro jogador pode jogar Cartas de Modificadores até o fim do seu turno.",
    card_expansion: true,
    card_id: 107,
    card_name: "Stagguard",
    card_name_br: "Guarda Veado",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Druid",
    card_class_br: "Druida",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_extra: "Two Item cards allowed to be attached to this Hero.",
    card_extra_br: "Este Herói pode equipar 2 cartas de Item.",
    card_effect: "7+ You may play up to 2 Item cards immediately.",
    card_effect_br: "7+ Você pode jogar até 2 Cartas de Item imediatamente.",
    card_expansion: true,
    card_id: 108,
    card_name: "Agile Dagger",
    card_name_br: "Adaga Ágil",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Warrior",
    card_class_br: "Guerreiro",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "8+ Choose any player. Return all equipped Item cards in that player's Party to your hand.",
    card_effect_br:
      "8+ Escolha qualquer jogador. Retorne todos as Cartas de Item equipadas no Grupo deste jogador para a sua mão",
    card_expansion: true,
    card_id: 109,
    card_name: "Blinding Blade",
    card_name_br: "Espada Cegante",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Warrior",
    card_class_br: "Guerreiro",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_extra: "Two Item cards allowed to be attached to this Hero.",
    card_extra_br: "Este Herói pode equipar 2 cartas de Item.",
    card_effect:
      "8+ +4 to your rolls to ATTACK a Monster card until the end of your turn.",
    card_effect_br:
      "8+ +4 para as suas roldas de ATAQUE à Cartas de Monstro até o fim do seu turno.",
    card_expansion: true,
    card_id: 110,
    card_name: "Critical Fang",
    card_name_br: "Presa Crítica",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Warrior",
    card_class_br: "Guerreiro",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "9+ DRAW a card for each Monster card in each other player's Party.",
    card_effect_br:
      "9+ COMPRE uma carta para cada Carta de Monstro no Grupo de cada outro jogador.",
    card_expansion: true,
    card_id: 111,
    card_name: "Hardened Hunter",
    card_name_br: "Caçador Endurecido",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Warrior",
    card_class_br: "Guerreiro",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_extra: "Two Item cards allowed to be attached to this Hero.",
    card_extra_br: "Este Herói pode equipar 2 cartas de Item.",
    card_effect:
      "5+ DRAW a card for each Item card equipped to a Hero card in your Party.",
    card_effect_br:
      "5+ COMPRE uma carta para cada Carta de Item equipado à uma Carta de Herói no seu Grupo.",
    card_expansion: true,
    card_id: 112,
    card_name: "Looting Lupo",
    card_name_br: "Lobo Saqueador",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Warrior",
    card_class_br: "Guerreiro",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "6+ For the rest of your turn, if you SACRIFICE or DESTROY a Hero card, you may search the discard pile for a Hero card and add it to your hand.",
    card_effect_br:
      "6+ Pelo o resto do seu turno, se você SACRIFICOU ou DESTRUIU uma Carta de Herói, você pode procurar na pilha de descarte por uma Carta de Herói e adiciona-la à sua mão.",
    card_expansion: true,
    card_id: 113,
    card_name: "Silent Shield",
    card_name_br: "Escudo Silencioso",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Warrior",
    card_class_br: "Guerreiro",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_extra: "Two Item cards allowed to be attached to this Hero.",
    card_extra_br: "Este Herói pode equipar 2 cartas de Item.",
    card_effect: "8+ For each Monster card in your Party, STEAL a Hero.",
    card_effect_br:
      "8+ Para cada Carta de Monstro no seu Grupo, ROUBE um Herói.",
    card_expansion: true,
    card_id: 114,
    card_name: "Tenacious Timber",
    card_name_br: "Tronco Persistente",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Warrior",
    card_class_br: "Guerreiro",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "5+ For each other Hero card in your party, +1 to all of your rolls until the end of your turn.",
    card_effect_br:
      "5+ Para cada outra Carta de Herói no seu Grupo, +1 para todas as suas roladas até o fim do seu turno.",
    card_expansion: true,
    card_id: 115,
    card_name: "Wolfgang Pack",
    card_name_br: "Bando Gangue-de-Lobo",
    card_type: "Hero Card",
    card_type_br: "Carta de Herói",
    game: "Here To Slay",
    card_class: "Warrior",
    card_class_br: "Guerreiro",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "You may roll to use the equipped Hero card's effect more than once per turn, at a cost of one action point for each roll to use.",
    card_effect_br:
      "Você pode rolar para usar o efeito da Carta de Herói equipada mais de uma vez por turno, com o custo de um ponto de ação para cada rolada que você fizer.",
    card_expansion: true,
    card_id: 116,
    card_name: "Bottomless Bag",
    card_name_br: "Bolsa Sem Fundo",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "The equipped Hero card is considered a Druid instead of its original class.",
    card_effect_br:
      "A Carta de Herói equipada é considerada um Druida ao invés da sua classe original.",
    card_expansion: true,
    card_id: 117,
    card_name: "Druid Mask",
    card_name_br: "Máscara do Druida",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "Each time you roll to use the equipped Hero card's effect, +4 to your roll.",
    card_effect_br:
      "Cada vez que você rolar para usar o efeito da Carta de Herói equipada, +4 para a sua rolada.",
    card_expansion: true,
    card_id: 118,
    card_name: "Even Bigger Ring",
    card_name_br: "Anel Ainda Maior",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "If you unsuccessfully roll to use the equipped Herocard's effect. you may spend an extra action point this turn.",
    card_effect_br:
      "Se você rolar sem sucesso para usar o efeito da Carta de Herói equipada, você pode gastar um ponto de ação extra este turno.",
    card_expansion: true,
    card_id: 119,
    card_name: "Temporal Hourglass",
    card_name_br: "Ampulheta Temporal",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "The equipped Hero card is considered a Warrior instead of its original class.",
    card_effect_br:
      "A Carta de Herói equipada é considerada um Guerreiro ao ao invés da sua classe original.",
    card_expansion: true,
    card_id: 120,
    card_name: "Warrior Mask",
    card_name_br: "",
    card_type: "Items",
    card_type_br: "Items",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "If another Hero card in your Party is stolen, move the equipped Hero card to the Party of the player who stole it as well.",
    card_effect_br:
      "Se outra Carta de Herói no seu Grupo for roubada, também mova a Carta de Herói equipada com Luvas Amaldiçoadas para o Grupo do jogador que roubou.",
    card_expansion: true,
    card_id: 121,
    card_name: "Cursed Glove",
    card_name_br: "Luva Amaldiçoada",
    card_type: "Cursed Items",
    card_type_br: "Items Amaldiçoados",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "If any Hero card in your Party is sacrificed or destroyed. SACRIFICE the equipped Hero card.",
    card_effect_br:
      "Se qualquer Carta de Herói do seu Grupo for sacrificada ou destruída, SACRIFIQUE a Carta de Herói equipada.",
    card_expansion: true,
    card_id: 122,
    card_name: "Soul Tether",
    card_name_br: "Corrente das Almas",
    card_type: "Cursed Items",
    card_type_br: "Items Amaldiçoados",
    game: "Here To Slay",
    card_class: "Item",
    card_class_br: "Item",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "Play this card after any player (including you) rolls the dice. +1 or -1 to that roll. DRAW 2 cards.",
    card_effect_br:
      "Jogue esta carta depois de qualquer jogador (incluindo você) rolar o dado. +1 ou -1 para essa rolada. COMPRE 2 cartas.",
    card_expansion: true,
    card_id: 123,
    card_name: "Modifier +1/-1",
    card_name_br: "Modificador +1/-1",
    card_type: "Modifier Card",
    card_type_br: "Carta de Modificador",
    game: "Here To Slay",
    card_class: "Modifiers",
    card_class_br: "Modificadores",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "Play this card after any player (including you) rolls the dice. +2 or -1 to that roll. DRAW a card.",
    card_effect_br:
      "Jogue esta carta depois de qualquer jogador (incluindo você) rolar o dado. +2 ou -1 para essa rolada. COMPRE uma carta.",
    card_expansion: true,
    card_id: 124,
    card_name: "Modifier +2/-1",
    card_name_br: "Modificador +2/-1",
    card_type: "Modifier Card",
    card_type_br: "Carta de Modificador",
    game: "Here To Slay",
    card_class: "Modifiers",
    card_class_br: "Modificadores",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "Play this card after any player (including you) rolls the dice. +4 to that roll. If the roll is modified above 12, DRAW a card.",
    card_effect_br:
      "Jogue esta carta depois de qualquer jogador (incluindo você) rolar o dado. +4 para essa rolada. Se a rolada for modificada para mais do que 12, COMPRE uma carta.",
    card_expansion: true,
    card_id: 125,
    card_name: "Modifier +4",
    card_name_br: "Modificador +4",
    card_type: "Modifier Card",
    card_type_br: "Carta de Modificador",
    game: "Here To Slay",
    card_class: "Modifiers",
    card_class_br: "Modificadores",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "Play this card after any player (including you) rolls the dice. -4 to that roll. If the roll is modified below 2, choose a card from the discard pile and add it to your hand.",
    card_effect_br:
      "Jogue esta carta depois de qualquer jogador (incluindo você) rolar o dado. -4 para essa rolada. Se a rolada for modificada para menos que 2, escolha uma carta da pilha de descarte e adicione-a à sua mão.",
    card_expansion: true,
    card_id: 126,
    card_name: "Modifier -4",
    card_name_br: "Modificador -4",
    card_type: "Modifier Card",
    card_type_br: "Carta de Modificador",
    game: "Here To Slay",
    card_class: "Modifiers",
    card_class_br: "Modificadores",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "Move all face-up Monster cards to the bottom of the Monster deck and flip the top 3 cards from the Monster deck face up. You may spend an extra action point this turn.",
    card_effect_br:
      "Mova todos as Cartas de Monstro abertas para o fundo do Baralho de Monstro e abra 3 novas Cartas de Monstro do Baralho. Você pode gastar um ponto de ação extra neste turno.",
    card_expansion: true,
    card_id: 127,
    card_name: "Beast Call",
    card_name_br: "Chamado da Besta",
    card_type: "Magic Card",
    card_type_br: "Carta Mágica",
    game: "Here To Slay",
    card_class: "Magic",
    card_class_br: "Mágica",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "DISCARD every card in your hand (if you have any) and DRAW 4 cards.",
    card_effect_br:
      "DESCARTE todas as cartas da sua mão (se você tiver alguma) e COMPRE 4 cartas.",
    card_expansion: true,
    card_id: 128,
    card_name: "Rapid Refresh",
    card_name_br: "Atualização Veloz",
    card_type: "Magic Card",
    card_type_br: "Carta Mágica",
    game: "Here To Slay",
    card_class: "Magic",
    card_class_br: "Mágica",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "You may play this card when another player attempts to play a Hero, Item, or Magic card. CHALLENGE that card. +3 to your roll.",
    card_effect_br:
      "Você pode jogar esta carta quando outro jogador tentar jogar uma carta de Herói, Item ou Mágica. DESAFIE aquela carta. +3 para a sua rolada.",
    card_expansion: true,
    card_id: 129,
    card_name: "Druid Challenge",
    card_name_br: "Desafio do Druida",
    card_type: "Challenge Card",
    card_type_br: "Carta de Desafio",
    game: "Here To Slay",
    card_class: "Challenge",
    card_class_br: "Desafio",
    card_requirements:
      "You need to have a Druid Hero in your Party to use this card",
    card_requirements_br:
      "Você precisa ter um Herói Druida no seu Grupo para jogar esta carta.",
  },
  {
    card_edition: "Warrior & Druids",
    card_edition_br: "Expansão Guerreiro e Druida",
    card_effect:
      "You may play this card when another player attempts to play a Hero, Item, or Magic card. CHALLENGE that card. +3 to your roll.",
    card_effect_br:
      "Você pode jogar esta carta quando outro jogador tentar jogar uma carta de Herói, Item ou Mágica. DESAFIE aquela carta. +3 para a sua rolada.",
    card_expansion: true,
    card_id: 130,
    card_name: "Warrior Challenge",
    card_name_br: "Desafio do Guerreiro",
    card_type: "Challenge Card",
    card_type_br: "Carta de Desafio",
    game: "Here To Slay",
    card_class: "Challenge",
    card_class_br: "Desafio",
    card_requirements:
      "You need to have a Warrior Hero in your Party to use this card",
    card_requirements_br:
      "Você precisa ter um Herói Guerreiro no seu Grupo para jogar esta carta.",
  },

  // ========================================================================================================================
  // MONSTERS EXPANSION
  // ========================================================================================================================

  {
    card_edition: "Monster Expansion",
    card_edition_br: "Expansão Monstros",
    card_effect:
      "Each time you roll to ATTACK a Monster card, +1 to that roll.",
    card_effect_br:
      "Cada vez que você rolar para ATACAR uma Carta de Monstro, +1 para a sua rolada.",
    card_expansion: true,
    card_id: 131,
    card_name: "Ancient Megashark",
    card_name_br: "Maga Tubarão Ancestral ",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Any Hero + DISCARD a card.",
    card_requirements_br: "1 Herói Qualquer + DESCARTE uma carta.",
    slay_conditions_lose: "6- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "6- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "9+ SLAY this Monster Card",
    slay_conditions_win_br: "9+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Monster Expansion",
    card_edition_br: "Expansão Monstros",
    card_effect:
      "Each time you end your turn with no cards in your hand, you may pull 2 cards from another player's hand.",
    card_effect_br:
      "Cada vez que você terminar seu turno sem cartas na mão, você pode pegar 2 cartas da mão de outro jogador.",
    card_expansion: true,
    card_id: 132,
    card_name: "Clawed Nightmare",
    card_name_br: "Pesadelo Com Garras",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Bard + 1 Thief + 1 Any",
    card_requirements_br: "1 Bardo + 1 Ladrão + 1 Qualquer",
    slay_conditions_lose: "6- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "6- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "9+ SLAY this Monster Card",
    slay_conditions_win_br: "9+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Monster Expansion",
    card_edition_br: "Expansão Monstros",
    card_effect:
      "Each time one of your Hero cards would be sacrificed or destroyed, you may DISCARD 2 cards instead.",
    card_effect_br:
      "Cada vez que uma das suas Cartas de Herói for sacrificada ou destruida, ao invés disso você pode DESCARTAR 2 cartas.",
    card_expansion: true,
    card_id: 133,
    card_name: "Dragon Wasp",
    card_name_br: "Vespa Dragão",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Any + DISCARD 2 cards.",
    card_requirements_br: "1 Qualquer + DESCARTE 2 cartas",
    slay_conditions_lose: "6- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "6- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "7+ SLAY this Monster Card",
    slay_conditions_win_br: "7+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Monster Expansion",
    card_edition_br: "Expansão Monstros",
    card_effect:
      "Each time you end your turn with no cards in your hand, you may DRAW 3 cards.",
    card_effect_br:
      "Cada vez que você terminar o seu turno sem cartas na mão, você pode COMPRAR 3 cartas.",
    card_expansion: true,
    card_id: 134,
    card_name: "Goretelodont",
    card_name_br: "Presalodonte",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Guardian + 1 Ranger + 1 Any",
    card_requirements_br: "1 Guardião + 1 Caçador + 1 Qualquer",
    slay_conditions_lose: "6- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "6- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "9+ SLAY this Monster Card",
    slay_conditions_win_br: "9+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Monster Expansion",
    card_edition_br: "Expansão Monstros",
    card_effect:
      "Each time you would DRAW a card, you may DRAW 2 cards and DISCARD a card instead.",
    card_effect_br:
      "Cada vez que você for COMPRAR uma carta, ao invés disso, você pode COMPRAR 2 cartas e DESCARTAR uma carta.",
    card_expansion: true,
    card_id: 135,
    card_name: "Lumbering Demon",
    card_name_br: "Demônio Entroncado",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "2 Any Heroes",
    card_requirements_br: "2 Heróis Quaisquer",
    slay_conditions_lose: "5- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "5- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "8+ SLAY this Monster Card",
    slay_conditions_win_br: "8+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Monster Expansion",
    card_edition_br: "Expansão Monstros",
    card_effect: "Each time you play a Challenge card, DRAW a card.",
    card_effect_br:
      "Cada vez que você jogar uma Carta de Desafio, COMPRE uma carta.",
    card_expansion: true,
    card_id: 136,
    card_name: "Possessed Plush",
    card_name_br: "Pelúcia Possuída",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Any + DISCARD a Challenge card",
    card_requirements_br: "1 Qualquer + DESCARTE uma Carta de Desafio",
    slay_conditions_lose: "4- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "4- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "7+ SLAY this Monster Card",
    slay_conditions_win_br: "7+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Monster Expansion",
    card_edition_br: "Expansão Monstros",
    card_effect:
      "Each time you unsuccessfully roll to use a Hero card's effect, you may DRAW a card.",
    card_effect_br:
      "Cada vez que você rolar sem sucesso para usar o efeito de uma Carta de Herói, você pode COMPRAR uma carta.",
    card_expansion: true,
    card_id: 137,
    card_name: "Reef Ripper",
    card_name_br: "Estripador do Recife",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Any Hero",
    card_requirements_br: "1 Herói Qualquer",
    slay_conditions_lose: "6- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "6- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "9+ SLAY this Monster Card",
    slay_conditions_win_br: "9+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Monster Expansion",
    card_edition_br: "Expansão Monstros",
    card_effect:
      "Each time one of your Hero cards is sacrificed or destroyed, you may play a Hero card from your hand immediately.",
    card_effect_br:
      "Cada vez que uma das suas Cartas de Herói for sacrificada ou destruída, voce pode jogar uma Carta de Herói da sua mão imediatamente.",
    card_expansion: true,
    card_id: 138,
    card_name: "Saffyre Phoenix",
    card_name_br: "Fênix do Fogo Azul-Safira",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Any Hero",
    card_requirements_br: "1 Herói Qualquer",
    slay_conditions_lose: "8- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "8- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "13+ SLAY this Monster Card.",
    slay_conditions_win_br: "13+ DESTRUA essa Carta de Monstro.",
    game: "Here To Slay",
    card_extra: "For each additional Hero card in your Party, +2 to your roll.",
    card_extra_br:
      "Para cada Carta de Herói adicional no seu Grupo, +2 para a sua rolada.",
  },
  {
    card_edition: "Monster Expansion",
    card_edition_br: "Expansão Monstros",
    card_effect:
      "Each time you end your turn with no cards in your hand, you may STEAL a Hero card.",
    card_effect_br:
      "Cada vez que você terminar o seu turno sem cartas na mão, você pode ROUBAR uma Carta de Herói.",
    card_expansion: true,
    card_id: 139,
    card_name: "Scavenger Griffin",
    card_name_br: "Grifo Catador",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Fighter + 1 Wizard + 1 Any",
    card_requirements_br: "1 Lutador + 1 Mago + 1 Qualquer",
    slay_conditions_lose: "6- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "6- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "9+ SLAY this Monster Card",
    slay_conditions_win_br: "9+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Monster Expansion",
    card_edition_br: "Expansão Monstros",
    card_effect: "Venomous Gemini counts for 2 Monsters",
    card_effect_br: "Gêmeas Venenosas contam como 2 Monstros",
    card_expansion: true,
    card_id: 140,
    card_name: "Venomous Gemini",
    card_name_br: "Gêmeas Venenosas",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "5 Any Heroes",
    card_requirements_br: "5 Heróis Quaisquer",
    slay_conditions_lose: "6- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "6- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "7+ SLAY this Monster Card",
    slay_conditions_win_br: "7+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Monster Expansion",
    card_edition_br: "Expansão Monstros",
    card_effect: "Each time you play a Magic card, DRAW a card.",
    card_effect_br:
      "Cada vez que você jogar uma Carta Mágica, COMPRE uma carta.",
    card_expansion: true,
    card_id: 141,
    card_name: "Voltclaw Lion",
    card_name_br: "Leão da Garra-Elétrica",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Any + Discard a Magic card",
    card_requirements_br: "1 Qualquer + Descarte uma Carta Mágica",
    slay_conditions_lose: "4- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "4- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "7+ SLAY this Monster Card",
    slay_conditions_win_br: "7+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
  {
    card_edition: "Monster Expansion",
    card_edition_br: "Expansão Monstros",
    card_effect:
      "Each time one of your Hero cards is sacrificed, you may DRAW a card.",
    card_effect_br:
      "Cada vez que uma das suas Cartas de Herói for sacrificada, você pode COMPRAR uma carta.",
    card_expansion: true,
    card_id: 142,
    card_name: "Wandering Behemoth",
    card_name_br: "Behemoth Vagante",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Any Hero",
    card_requirements_br: "1 Herói Qualquer",
    slay_conditions_lose: "6- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "6- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "10+ SLAY this Monster Card",
    slay_conditions_win_br: "10+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
    card_extra: "For each additional Hero card in your Party, +1 to your roll.",
    card_extra_br:
      "Para cada Carta de Herói adicional no seu Grupo, +1 para a sua rolada.",
  },
  {
    card_edition: "Monster Expansion",
    card_edition_br: "Expansão Monstros",
    card_effect: "Each time you play an Item card, DRAW a card.",
    card_effect_br: "Cada vez que você jogar um Item, COMPRE uma carta.",
    card_expansion: true,
    card_id: 143,
    card_name: "Wicked Sea Serpent",
    card_name_br: "Serpente do Mar Perversa",
    card_type: "Monster",
    card_type_br: "Monstro",
    card_requirements: "1 Any + DISCARD an Item card",
    card_requirements_br: "1 Herói Qualquer + DESCARTE um Item",
    slay_conditions_lose: "4- SACRIFICE a Hero Card",
    slay_conditions_lose_br: "4- SACRIFIQUE uma Carta de Herói",
    slay_conditions_win: "7+ SLAY this Monster Card",
    slay_conditions_win_br: "7+ DESTRUA essa Carta de Monstro",
    game: "Here To Slay",
  },
];

export default htsCards;
