const hldCards = [
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "Your beach day turns into a whale of a surprise...",
    card_flavor_br:
      "Seu dia na praia se transforma numa baleia de surpresas...",
    card_id: 1,
    card_name: "A Day at the Beach",
    card_name_br: "Um Dia na Praia",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "The tiny dinos looked adorable until they threatened to kill you and your family.",
    card_flavor_br:
      "Os minúsculos dinossauros pareciam adoráveis até que ameaçaram matar você e sua família.",
    card_id: 2,
    card_name: "Armed And Dangerous",
    card_name_br: "Armado e Perigoso",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "You try to cut your own hair. You watch as your self-esteem falls to the floor.",
    card_flavor_br:
      "Você tenta cortar o seu próprio cabelo. Você observa enquanto sua auto-estima vai para o chão.",
    card_id: 3,
    card_name: "Baddest Hair Day",
    card_name_br: "Dia do Pior Cabelo",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "The sun isn't actually that bright, they said. You proved them wrong.",
    card_flavor_br:
      "O Sol não é realmente tão brilhante, eles disseram. Você provou que eles estavão errados.",
    card_id: 4,
    card_name: "Bright Idea",
    card_name_br: "Ideia Brilhante",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "You are hiking a volcano that's been dormant for thousands of years. It erupts.",
    card_flavor_br:
      "Você está caminhando por um vulcão adormecido por milhares de anos. Ele entra em erupção.",
    card_id: 5,
    card_name: "Casual Afternoon Stroll",
    card_name_br: "Passeio Casual à Tarde",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "When it rains, it pours...but only on you.",
    card_flavor_br: "Quanto chove, pinga...mas apenas em você.",
    card_id: 6,
    card_name: "Downpour",
    card_name_br: "Aguaceiro",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "Looks like your ex is better off without you after all...",
    card_flavor_br:
      "Parece que sua ex está melhor sem você no fim das contas...",
    card_id: 7,
    card_name: "Emergency Ex-it",
    card_name_br: '"Saida" de Emergência',
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "Life is going great!... Just kidding of course. You are attacked by sabertoothed squirrels.",
    card_flavor_br:
      "A vida está ótima!... Brincadeira, claro. Você foi atacado por esquilos dente-de-sabre.",
    card_id: 8,
    card_name: "Feeling Squirrely",
    card_name_br: "Sentindo-se Esqui-sito",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "Prehistoric fire ants unleash their wrath on you for taking a nap on their hill.",
    card_flavor_br:
      "Formigas de fogo pré-históricas liberam sua ira em você por tirar um cochilo em sua colina.",
    card_id: 9,
    card_name: "Fired Up",
    card_name_br: "Esquentado",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "You get ghosted by your dino date. 'They must actually be dead,' you say to yourself as your tears salt your dinner for one.",
    card_flavor_br:
      'Você foi esquecido pelo seu dino date. "Eles devem estar mortos," você diz para si mesmo enquanto suas lágrimas salgam seu jantar para um.',
    card_id: 10,
    card_name: "Ghosted",
    card_name_br: "Esquecido",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "You get cut by a particularly sharp leaf.",
    card_flavor_br: "Você é cortado por uma folha particularmente afiada ",
    card_id: 11,
    card_name: "Leaf Me Alone",
    card_name_br: '"Folha" Daqui',
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "Your friends plan a road trip without you. The exhaust fumes hit you as they drive away.",
    card_flavor_br:
      "Seus amigos planejaram uma viagem sem você. A fumaça do escapamento te acerta enquanto eles vão embora.",
    card_id: 12,
    card_name: "Left Behind...Again",
    card_name_br: "Deixado para Trás...Denovo",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "Maybe next time you should think twice before babysitting a carnivore.",
    card_flavor_br:
      "Talvez na próxima vez você devesse pensar duas vezes antes de ser babá de um carnivoro.",
    card_id: 13,
    card_name: "Lil' Cannibal",
    card_name_br: "Pequeno Canibal",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "All you want is to be loved. A boa constrictor gives you a 'hug.' You're thrilled.",
    card_flavor_br:
      'Tudo o que você quer é ser amado. Uma Jobóia te da um "abraço". Você está emocionado.',
    card_id: 14,
    card_name: "Love Hurts",
    card_name_br: "O Amor Dói",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "This card acts as any type of Disaster card.",
    card_effect_br:
      "Essa carta funciona como qualquer tipo de Carta de Desastre.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 15,
    card_name: "Meteor!",
    card_name_br: "Meteoro!",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "The cookies you were looking forward to all day burned to a crisp.",
    card_flavor_br:
      "Os biscoitos que você esperou o dia todo queimaram até ficarem crocantes.",
    card_id: 16,
    card_name: "Ooh, Burn...",
    card_name_br: "Ooh, Queimou...",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "Are the other dinosaurs really talking about you? Yes.",
    card_flavor_br:
      "Os outros dinossauros estão realmente falando de você? Sim.",
    card_id: 17,
    card_name: "Outer Circle",
    card_name_br: "Círculo Externo",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "Just your average day, running in horror from a FREAKING LAND SHARK.",
    card_flavor_br:
      "Apenas um dia normal, correndo horrorizado de um MALDITO TUBARÃO TERRESTRE",
    card_id: 18,
    card_name: "Shark With Legs",
    card_name_br: "Tubarão Com Pernas",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "Your relaxing spa day turns into tragedy as you start to sink in hot tar.",
    card_flavor_br:
      "O seu dia relaxante no spa vira uma tragédia quando você começa a afundar em oleo quente",
    card_id: 19,
    card_name: "Spa Day",
    card_name_br: "Dia no Spa",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "You're crushed by a mega dino and your herd awkwardly walks away.",
    card_flavor_br:
      "Você é esmagado por um mega dinossauro e o seu rebanho se afasta de forma estranha.",
    card_id: 20,
    card_name: "Stomped",
    card_name_br: "Pisoteado",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "You visit a fortune teller and the crystal ball explodes...that can't be a good sign.",
    card_flavor_br:
      "Você visita uma cartomante e a bola de cristal explode... isso não pode ser um bom sinal.",
    card_id: 21,
    card_name: "The Future Is Bleak",
    card_name_br: "O Futuro é Sombrio",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "You lie awake at night thinking about how much of a disappointment you are.",
    card_flavor_br:
      "Você passa a noite acordado pensando em como você é uma decepção.",
    card_id: 22,
    card_name: "The Sad Truth",
    card_name_br: "A Triste Verdade",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "A small earthquake hits that seems to have happened only under you. You fall through a crack in the earth.",
    card_flavor_br:
      "Um pequeno terremoto acontece aparentemente apenas sob você. Você cai por uma rachadura na terra.",
    card_id: 23,
    card_name: "This Feels Personal",
    card_name_br: "Isso Parece Pessoal",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "If a tree falls on you in a forest and no one is around to save you, is this your new life now?",
    card_flavor_br:
      "Se uma arvore cai em você no meio da floresta e ninguem está por perto para te salvar, essa é a sua nova vida agora?",
    card_id: 24,
    card_name: "Trapped",
    card_name_br: "Preso",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor:
      "Is it just a cough...or are you secretly dying? Time to start panicking.",
    card_flavor_br:
      "É apenas uma tosse...ou você está secretamente morrendo? Hora de entrar em pânico.",
    card_id: 25,
    card_name: "Uncommon Cold",
    card_name_br: "Gripe Incomum",
    card_type: "Disaster Card",
    card_type_br: "Carta de Desastre",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 26,
    card_name: "Bonehead",
    card_name_br: "Cabeça de Osso",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 27,
    card_name: "Bow And Dino",
    card_name_br: "Arco e Dinossauro",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 28,
    card_name: "Cool Stick",
    card_name_br: "Graveto Legal",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "You may discard a Point card with an effect from your hand, then add its point value to your score this round.",
    card_effect_br:
      "Você pode descartar uma Carta de Ponto com um efeito da sua mão, adicione esses pontos à sua pontuação nesta rodada.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 29,
    card_name: "'Delicious' Smoothie",
    card_name_br: 'Smoothie "Delicioso"',
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "You may look at another player's hand. Choose a card and add it to your hand.",
    card_effect_br:
      "Você pode olhar a mão de um outro jogador. Escolha uma carta e coloque na sua mão.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 30,
    card_name: "Dino Grabber",
    card_name_br: "Dinossauro Agarrador",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "You may discard up to 3 cards from your hand.",
    card_effect_br: "Você pode descartar até 3 cartas da sua mão.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 31,
    card_name: "Fire Spray",
    card_name_br: "Spray de Fogo",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "During this round, all other Point card effects are ignored.",
    card_effect_br:
      "Durante essa rodada, todos os outros efeitos de Cartas de Ponto são ignorados.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 32,
    card_name: "Flaming Chainsaw",
    card_name_br: "Motosserra Flamejante",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "You may swap this card with the Point card of the player to your right or left. You cannot swap for a card that has an effect.",
    card_effect_br:
      "Você pode trocar essa carta com a Carta de Ponto do jogador à sua direita ou esquerda. Você não pode trocar por uma carta que tenha efeitos.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 33,
    card_name: "Grappling Snake",
    card_name_br: "Cobra Agarradora",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 34,
    card_name: "Grave Maker",
    card_name_br: "Criador de Cova",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 35,
    card_name: "Handy Pan",
    card_name_br: "Bandeja Prática",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 36,
    card_name: "Run Home Bat",
    card_name_br: 'Bastão "Corre pra Casa"',
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "You may swap the Point cards of any two other players.",
    card_effect_br:
      "Você pode trocar as Cartas de Ponto de quaisquer outros dois jogadores.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 37,
    card_name: "Hungry Plant",
    card_name_br: "Planta Faminta",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 38,
    card_name: "Iced Ptea",
    card_name_br: "Congelodáctilo",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 39,
    card_name: "Meteor Cannon",
    card_name_br: "Canhão Meteoro",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "During scoring this round, switch the score of the highest-scoring player with the score of the lowest-scoring player after scores have been calculated.",
    card_effect_br:
      "Durante a contagem de pontos deste turno, troque a pontuação do jogador com mais pontos com o jogador com menos pontos depois que as pontuações ja estiverem calculadas. ",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 40,
    card_name: "Mouth Trap",
    card_name_br: "Armadilha de Boca",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "You may discard a Point card from your hand, then add its point value to your score this round.",
    card_effect_br:
      "Você pode descartar uma Carta de Ponto da sua mão, adicione esses pontos à sua pontuação nesta rodada.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 41,
    card_name: "Pet Rock",
    card_name_br: "Pedra de Estimação",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "During scoring this round, double the effects of Score Booster and Score Sapper cards.",
    card_effect_br:
      "Durante a fase de pontuação desta rodada, dobre os efeitos das cartas Impulsionador de Pontos e Sapador de Pontos.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 42,
    card_name: "Special Star Fruit",
    card_name_br: "Fruta Estrela Especial",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect: "",
    card_effect_br: "",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 43,
    card_name: "Sting Stabber",
    card_name_br: "Picada Esfaqueadora",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "You may look at the top 2 cards in the deck. Choose a card and add it to your hand. Discard the other card.",
    card_effect_br:
      "Você pode olhar as duas primeira cartas do baralho. Escolha uma carta e adicione à sua mão. Descarta a outra carta.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 44,
    card_name: "Treenoculars",
    card_name_br: "Binóculos",
    card_type: "Point Card",
    card_type_br: "Carta de Ponto",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Play this card if you would add a Disaster card to your Disaster Area this round. Move that Disaster card to the bottom of the Disaster deck instead.",
    card_effect_br:
      "Jogue esta carta se você fosse adicionar uma Carta de Desastre à sua Área de Desastre nesta rodada. Mova a Carta de Desastre para o fundo do Baralho de Desastre",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 45,
    card_name: "Disaster Insurance",
    card_name_br: "Seguro contra Desastres",
    card_type: "Instant Card",
    card_type_br: "Carta Instantânea",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Play this card if you would add a Disaster card to your Disaster Area this round. Add that Disaster card to another player's Disaster Area instead.",
    card_effect_br:
      "Jogue esta carta se você fosse adicionar uma Carta de Desastre à sua Área de Desastre nesta rodada. Adicione a Carta de Desastre na Área de Desastre de outro jogador.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 46,
    card_name: "Disaster Redirect",
    card_name_br: "Redirecionador de Desastre",
    card_type: "Instant Card",
    card_type_br: "Carta Instantânea",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Play this card during scoring. Add 2 points to any player's score this round.",
    card_effect_br:
      "Jogue esta carta durante a pontuação. Adicione 2 pontos para qualquer jogador nessa rodada.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 47,
    card_name: "Score Booster",
    card_name_br: "Impulsionador de Pontos",
    card_type: "Instant Card",
    card_type_br: "Carta Instantânea",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Play this card during scoring. Switch the score of the highest-scoring player with the score of the lowest-scoring player after scores have been calculated.",
    card_effect_br:
      "Jogue esta carta durante a pontuação. Troque os pontos do jogador com mais pontos com o jogador com menos pontos depois que as pontuações ja estiverem calculadas.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br: "",
    card_id: 48,
    card_name: "Score Inversion",
    card_name_br: "Inversão de Pontos",
    card_type: "Instant Card",
    card_type_br: "Carta Instantânea",
    game: "Happy Little Dinosaurs",
  },
  {
    card_edition: "Base Game",
    card_edition_br: "Jogo Base",
    card_effect:
      "Play this card during scoring. Subtract 2 points from any player's score this round.",
    card_effect_br:
      "Jogue esta carta durante a pontuação. Subtraia 2 pontos de qualquer jogador nessa rodada.",
    card_expansion: false,
    card_flavor: "",
    card_flavor_br:
      "Apenas de curiosidade!! Sapador é o soldado do exército responsável por cavar trincheiras e fossos.",
    card_id: 49,
    card_name: "Score Sapper",
    card_name_br: "Sapador de Pontos",
    card_type: "Instant Card",
    card_type_br: "Carta Instantânea",
    game: "Happy Little Dinosaurs",
  },
];

export default hldCards;
