const htsCards = [
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': 'Each time you roll to CHALLENGE, +2 to your roll.',
        'card_effect_br': 'Cada vez que você rolar para DESAFIAR. +2 para a sua rolada.',
        'card_extra': 'The effect is active when the challenge is initiated by the controlling player. Not all challenges',
        'card_extra_br': 'O efeito é ativado quando o desafio é iniciado pelo jogador que o controla. Não em todos os desafios',
        'card_expansion': false,
        'card_flavor': '',
        'card_flavor_br': '',
        'card_id': 1,
        'card_name': 'The Fist of Reason',
        'card_name_br': 'O Punho da Razão',
        'card_type': 'Party Leader',
        'card_type_br': 'Líder de Grupo',
        'card_class': 'Fighter',
        'card_class_br': 'Lutador',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you roll to use a Hero card's effect, +1 to your roll.",
        'card_effect_br': 'Cada vez que você rolar para usar um efeito de Carta de Heroi, +1 para a sua rolada.',
        'card_extra': '',
        'card_extra_br': '',
        'card_expansion': false,
        'card_flavor': '',
        'card_flavor_br': '',
        'card_id': 2,
        'card_name': 'The Charismatic Song',
        'card_name_br': 'A Canção Carismática',
        'card_type': 'Party Leader',
        'card_type_br': 'Líder de Grupo',
        'card_class': 'Bard',
        'card_class_br': 'Bardo',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you play a Modifier card on a roll, +1 or -1 to that roll.",
        'card_effect_br': 'Cada vez que você jogar uma carta de Modificador numa rolada, +1 ou -1 para essa rolada.',
        'card_extra': '',
        'card_extra_br': '',
        'card_expansion': false,
        'card_flavor': '',
        'card_flavor_br': '',
        'card_id': 3,
        'card_name': 'The Protecting Horn',
        'card_name_br': 'O Chifre Protetor',
        'card_type': 'Party Leader',
        'card_type_br': 'Líder de Grupo',
        'card_class': 'Guardian',
        'card_class_br': 'Guardião',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you roll to ATTACK a Monster card, +1 to your roll.",
        'card_effect_br': 'Cada vez que você rolar para ATACAR uma Carta de Monstro, +1 para a sua rolada.',
        'card_extra': '',
        'card_extra_br': '',
        'card_expansion': false,
        'card_flavor': '',
        'card_flavor_br': '',
        'card_id': 4,
        'card_name': 'The Divine Arrow',
        'card_name_br': 'A Flecha Divina',
        'card_type': 'Party Leader',
        'card_type_br': 'Líder de Grupo',
        'card_class': 'Ranger',
        'card_class_br': 'Caçador',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Once per turn on your turn, you may spend an action point to pull a card from another player's hand.",
        'card_effect_br': 'Uma vez por turno no seu turno, você pode gastar um ponto de ação para pegar uma carta da mão de outro jogador.',
        'card_extra': 'This card cannot be used in a 2 player game.',
        'card_extra_br': 'Essa carta não pode ser usada em jogos de 2 jogadores.',
        'card_expansion': false,
        'card_flavor': '',
        'card_flavor_br': '',
        'card_id': 5,
        'card_name': 'The Shadow Claw',
        'card_name_br': 'A Garra Sombria',
        'card_type': 'Party Leader',
        'card_type_br': 'Líder de Grupo',
        'card_class': 'Thief',
        'card_class_br': 'Ladrão',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you play a Magic card, DRAW a card.",
        'card_effect_br': 'Cada vez que você jogar uma Carta Mágica, COMPRE uma carta.',
        'card_extra': '',
        'card_extra_br': '',
        'card_expansion': false,
        'card_flavor': '',
        'card_flavor_br': '',
        'card_id': 6,
        'card_name': 'The Cloaked Sage',
        'card_name_br': 'O Sábio Camuflado',
        'card_type': 'Party Leader',
        'card_type_br': 'Líder de Grupo',
        'card_class': 'Wizard',
        'card_class_br': 'Mago',
        'game': 'Here To Slay'
    },
]


export default htsCards