const htsCards = [
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': 'Each time you roll to CHALLENGE, +2 to your roll.',
        'card_effect_br': 'Cada vez que você rolar para DESAFIAR. +2 para a sua rolada.',
        'card_extra': 'The effect is active when the challenge is initiated by the controlling player. Not all challenges',
        'card_extra_br': 'O efeito é ativado quando o desafio é iniciado pelo jogador que o controla. Não em todos os desafios',
        'card_expansion': false,
        'card_flavor': '',
        'card_flavor_br': '',
        'card_id': 1,
        'card_name': 'The Fist of Reason',
        'card_name_br': 'O Punho da Razão',
        'card_type': 'Party Leader',
        'card_type_br': 'Líder de Grupo',
        'card_class': 'Fighter',
        'card_class_br': 'Lutador',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you roll to use a Hero card's effect, +1 to your roll.",
        'card_effect_br': 'Cada vez que você rolar para usar um efeito de Carta de Heroi, +1 para a sua rolada.',
        'card_extra': '',
        'card_extra_br': '',
        'card_expansion': false,
        'card_flavor': '',
        'card_flavor_br': '',
        'card_id': 2,
        'card_name': 'The Charismatic Song',
        'card_name_br': 'A Canção Carismática',
        'card_type': 'Party Leader',
        'card_type_br': 'Líder de Grupo',
        'card_class': 'Bard',
        'card_class_br': 'Bardo',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you play a Modifier card on a roll, +1 or -1 to that roll.",
        'card_effect_br': 'Cada vez que você jogar um Modificador numa rolada, +1 ou -1 para essa rolada.',
        'card_extra': '',
        'card_extra_br': '',
        'card_expansion': false,
        'card_flavor': '',
        'card_flavor_br': '',
        'card_id': 3,
        'card_name': 'The Protecting Horn',
        'card_name_br': 'O Chifre Protetor',
        'card_type': 'Party Leader',
        'card_type_br': 'Líder de Grupo',
        'card_class': 'Guardian',
        'card_class_br': 'Guardião',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you roll to ATTACK a Monster card, +1 to your roll.",
        'card_effect_br': 'Cada vez que você rolar para ATACAR uma Carta de Monstro, +1 para a sua rolada.',
        'card_extra': '',
        'card_extra_br': '',
        'card_expansion': false,
        'card_flavor': '',
        'card_flavor_br': '',
        'card_id': 4,
        'card_name': 'The Divine Arrow',
        'card_name_br': 'A Flecha Divina',
        'card_type': 'Party Leader',
        'card_type_br': 'Líder de Grupo',
        'card_class': 'Ranger',
        'card_class_br': 'Caçador',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Once per turn on your turn, you may spend an action point to pull a card from another player's hand.",
        'card_effect_br': 'Uma vez por turno no seu turno, você pode gastar um ponto de ação para pegar uma carta da mão de outro jogador.',
        'card_extra': 'This card cannot be used in a 2 player game.',
        'card_extra_br': 'Essa carta não pode ser usada em jogos de 2 jogadores.',
        'card_expansion': false,
        'card_id': 5,
        'card_name': 'The Shadow Claw',
        'card_name_br': 'A Garra Sombria',
        'card_type': 'Party Leader',
        'card_type_br': 'Líder de Grupo',
        'card_class': 'Thief',
        'card_class_br': 'Ladrão',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you play a Magic card, DRAW a card.",
        'card_effect_br': 'Cada vez que você jogar uma Carta Mágica, COMPRE uma carta.',
        'card_expansion': false,
        'card_id': 6,
        'card_name': 'The Cloaked Sage',
        'card_name_br': 'O Sábio Camuflado',
        'card_type': 'Party Leader',
        'card_type_br': 'Líder de Grupo',
        'card_class': 'Wizard',
        'card_class_br': 'Mago',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time another player plays a Modifier card on one of your rolls, +1 to your roll.",
        'card_effect_br': 'Cada vez que outro jogador jogar um Modificador em uma carta sua, +1 para a sua rolada.',
        'card_expansion': false,
        'card_id': 7,
        'card_name': 'Abyss Queen',
        'card_name_br': 'Rainha do Abismo',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '5- SACRIFICE a Hero Card',
        'slay_conditions_lose_br': '5- SACRIFIQUE uma Carta de Herói',
        'slay_conditions_win': '8+ SLAY this Monster Card',
        'slay_conditions_win_br': '8+ DESTRUA essa Carta de Monstro',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you successfully roll to use a Hero's effect, DRAW a card.",
        'card_effect_br': 'Cada vez que você rolar com sucesso para usar um efeito de Herói, COMPRE uma carta.',
        'card_expansion': false,
        'card_id': 8,
        'card_name': 'Artic Aries',
        'card_name_br': 'O Carneiro do Artico',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '6- SACRIFICE a Hero Card',
        'slay_conditions_lose_br': '6- SACRIFIQUE uma Carta de Herói',
        'slay_conditions_win': '10+ SLAY this Monster Card',
        'slay_conditions_win_br': '10+ DESTRUA essa Carta de Monstro',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you roll, +1 to your roll.",
        'card_effect_br': 'Cada vez que você rolar, +1 para a sua rolada.',
        'card_expansion': false,
        'card_id': 9,
        'card_name': 'Anuran Cauldron',
        'card_name_br': 'Caldeirão Anuro',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '6- SACRIFICE a Hero Card',
        'slay_conditions_lose_br': '65- SACRIFIQUE uma Carta de Herói',
        'slay_conditions_win': '7+ SLAY this Monster Card',
        'slay_conditions_win_br': '7+ DESTRUA essa Carta de Monstro',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time another player CHALLENGES you, that player must DISCARD a card.",
        'card_effect_br': 'Cada vez que outro jogador DESAFIAR você, aquele jogador deverá DESCARTAR uma carta.',
        'card_expansion': false,
        'card_id': 10,
        'card_name': 'Bloodwing',
        'card_name_br': 'Asa Sangrenta',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '6- SACRIFICE a Hero Card',
        'slay_conditions_lose_br': '6- SACRIFIQUE uma Carta de Herói',
        'slay_conditions_win': '9+ SLAY this Monster Card',
        'slay_conditions_win_br': '9+ DESTRUA essa Carta de Monstro',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time another player plays a Modifier card on one of your rolls, +1 to your roll.",
        'card_effect_br': 'Cada vez que outro jogador jogar um Modificador em uma carta sua, +1 para a sua rolada.',
        'card_expansion': false,
        'card_id': 11,
        'card_name': 'Corrupted Sabretooth',
        'card_name_br': 'Dente-de-Sabre Corrompido',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '6- SACRIFICE a Hero Card',
        'slay_conditions_lose_br': '6- SACRIFIQUE uma Carta de Herói',
        'slay_conditions_win': '9+ SLAY this Monster Card and DRAW a card.',
        'slay_conditions_win_br': '9+ DESTRUA essa Carta de Monstro e COMPRE uma carta.',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time any player (including you) plays a Modifier card, you may DRAW a card.",
        'card_effect_br': 'Cada vez que qualquer jogador (você inclusive)  jogar um Modificador, você pode COMPRAR uma carta.',
        'card_expansion': false,
        'card_id': 12,
        'card_name': 'Crowned Serpent',
        'card_name_br': 'Serpente Coroada',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '7- SACRIFICE a Hero Card',
        'slay_conditions_lose_br': '7- SACRIFIQUE uma Carta de Herói',
        'slay_conditions_win': '10+ SLAY this Monster Card',
        'slay_conditions_win_br': '10+ DESTRUA essa Carta de Monstro',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time a Hero card in your Party is destroyed, you may DRAW a card.",
        'card_effect_br': 'Cada vez que uma Carta de Herói do seu grupo for destruído, você pode COMPRAR uma carta.',
        'card_expansion': false,
        'card_id': 13,
        'card_name': 'Dracos',
        'card_name_br': 'Dracos',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_win': '5- SLAY this Monster Card',
        'slay_conditions_win_br': '5- DESTRUA essa Carta de Monstro',
        'slay_conditions_lose': '8+ SACRIFICE a hero Card',
        'slay_conditions_lose_br': '8+ SACRIFIQUE uma Carta de Herói.',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you roll for a Hero card's effect, +1 to your roll.",
        'card_effect_br': 'Cada vez que você rolar para usar um efeito de carta de Herói, +1 para a sua rolada.',
        'card_expansion': false,
        'card_id': 14,
        'card_name': 'Dark Dragon King',
        'card_name_br': 'Rei Dragão Negro',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '4- DISCARD 2 cards',
        'slay_conditions_lose_br': '4- DESCARTE 2 cartas',
        'slay_conditions_win': '8+ SLAY this Monster Card',
        'slay_conditions_win_br': '8+ DESTRUA essa Carta de Monstro',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you DRAW an item card, you may play it immediately.",
        'card_effect_br': 'Cada vez que você COMPRAR uma Carta de Item, você pode joga-la imediatamente.',
        'card_expansion': false,
        'card_id': 15,
        'card_name': 'Malamammoth',
        'card_name_br': 'Malamammoth',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '4- DISCARD 2 cards',
        'slay_conditions_lose_br': '4- DESCARTE 2 cartas',
        'slay_conditions_win': '8+ SLAY this Monster Card',
        'slay_conditions_win_br': '8+ DESTRUA essa Carta de Monstro',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "You may spend an extra action point on each of your turns.",
        'card_effect_br': 'Você pode gastar um ponto de ação extra em cada um dos seus turnos.',
        'card_expansion': false,
        'card_id': 16,
        'card_name': 'Mega Slime',
        'card_name_br': 'Mega Slime',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '7- SACRIFICE a Hero Card',
        'slay_conditions_lose_br': '7- SACRIFIQUE uma Carta de Herói',
        'slay_conditions_win': '8+ SLAY this Monster Card & DRAW 2 cards',
        'slay_conditions_win_br': '8+ DESTRUA essa Carta de Monstro & COMPRE 2 cartas.',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you DRAW a Magic card, you may play it immediately.",
        'card_effect_br': 'Cada vez que você COMPRAR uma Carta Mágica, você pode joga-la imediatamente.',
        'card_expansion': false,
        'card_id': 17,
        'card_name': 'Orthus',
        'card_name_br': 'Orthus',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '4- DISCARD 2 cards',
        'slay_conditions_lose_br': '4- DESCARTE 2 cartas.',
        'slay_conditions_win': '8+ SLAY this Monster Card',
        'slay_conditions_win_br': '8+ DESTRUA essa Carta de Monstro',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you DRAW a Modifier card, you may reveal it and DRAW a second card.",
        'card_effect_br': 'Cada vez que você COMPRAR um Modificador, você pode revela-lo e COMPRAR uma segunda carta.',
        'card_expansion': false,
        'card_id': 18,
        'card_name': 'Rex Major',
        'card_name_br': 'Grande Rex',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '4- DISCARD 2 cards',
        'slay_conditions_lose_br': '4- DESCARTE 2 cartas',
        'slay_conditions_win': '8+ SLAY this Monster Card',
        'slay_conditions_win_br': '8+ DESTRUA essa Carta de Monstro',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Your Hero cards cannot be destroyed.",
        'card_effect_br': 'Suas Cartas de Herói não podem ser destruidas.',
        'card_expansion': false,
        'card_id': 19,
        'card_name': 'Terratuga',
        'card_name_br': 'Terratuga',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '7- SACRIFICE a Hero Card',
        'slay_conditions_lose_br': '7- SACRIFIQUE uma Carta de Herói',
        'slay_conditions_win': '11+ SLAY this Monster Card',
        'slay_conditions_win_br': '11+ DESTRUA essa Carta de Monstro',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Each time you roll for a Challenge card, +1 to your roll.",
        'card_effect_br': 'Cada vez que você rolar para uma Carta de Desafio, +1 para a sua rolada.',
        'card_expansion': false,
        'card_id': 20,
        'card_name': 'Titan Wyvern',
        'card_name_br': 'Wyvern Titã',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '4- DISCARD 2 cards',
        'slay_conditions_lose_br': '4- DESCARTE 2 cartas',
        'slay_conditions_win': '8+ SLAY this Monster Card',
        'slay_conditions_win_br': '8+ DESTRUA essa Carta de Monstro',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "Item cards you play cannot be challenged.",
        'card_effect_br': 'Cartas de Item que você jogar não podem ser desafiadas.',
        'card_expansion': false,
        'card_id': 21,
        'card_name': 'Warworn Owlbear',
        'card_name_br': 'Urso-Coruja Marcado pela Guerra',
        'card_type': 'Monster',
        'card_type_br': 'Monstro',
        'slay_conditions_lose': '4- DISCARD 2 cards',
        'slay_conditions_lose_br': '4- DESCARTE 2 cartas',
        'slay_conditions_win': '8+ SLAY this Monster Card',
        'slay_conditions_win_br': '8+ DESTRUA essa Carta de Monstro',
        'game': 'Here To Slay'
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "8+ DESTROY a Hero card.",
        'card_effect_br': '8+ DESTRUA uma Carta de Herói.',
        'card_expansion': false,
        'card_id': 22,
        'card_name': 'Bad Axe',
        'card_name_br': 'Machado Ruim',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Fighter',
        'card_class_br': 'Lutador',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "7+ Pull a card from another player's hand. If it is a Hero card, pull a second card from that player's hand.",
        'card_effect_br': '7+ Pegue uma carta da mão de outro jogador. se for uma Carta de Herói, pegue uma segunda carta da mão deste mesmo jogador.',
        'card_expansion': false,
        'card_id': 23,
        'card_name': 'Bear Claw',
        'card_name_br': 'Garra de Urso',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Fighter',
        'card_class_br': 'Lutador',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "7+ Each other player must DISCARD a card. Choose one of the discarded cards and add it to your hand.",
        'card_effect_br': '7+ Cada outro jogador deve DESCARTAR uma carta. Escolha uma das cartas descartadas desta maneira e coloque na sua mão.',
        'card_expansion': false,
        'card_id': 24,
        'card_name': 'Beary Wise',
        'card_name_br': 'Barburso Sábio',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Fighter',
        'card_class_br': 'Lutador',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "5+ Pull a card from another player's hand. If it is a Challenge card, pull a second card from that player's hand.",
        'card_effect_br': '5+ Pegue uma carta da mão de outro jogador. Se for uma Carta de DESAFIO, pegue uma segunda carta da mão deste mesmo jogador.',
        'card_expansion': false,
        'card_id': 25,
        'card_name': 'Fury Knuckle',
        'card_name_br': 'Articulações Furiosas',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Fighter',
        'card_class_br': 'Lutador',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "5+ Choose a player. That player must DISCARD 2 cards.",
        'card_effect_br': '5+ Escolha um jogador. Este jogador deve DESCARTAR 2 cartas.',
        'card_expansion': false,
        'card_id': 26,
        'card_name': 'Heavy Bear',
        'card_name_br': 'Urso Pesado',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Fighter',
        'card_class_br': 'Lutador',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "8+ DRAW 2 cards. If at least one of those cards is a Challenge card, you may reveal it, then DESTROY a Hero card.",
        'card_effect_br': '8+ COMPRE 2 cartas. Se pelo menos uma delas for uma carta de DESAFIO, você pode revela-la e DESTRUIR uma Carta de Herói.',
        'card_expansion': false,
        'card_id': 27,
        'card_name': 'Pan Chucks',
        'card_name_br': 'Panda Nunchaku',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Fighter',
        'card_class_br': 'Lutador',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "10+ DISCARD up to 3 cards. For each card discarded, DESTROY a Hero card.",
        'card_effect_br': '10+ DESCARTE até 3 cartas. Para cada carta descartada, DESTRUA uma Carta de Herói.',
        'card_expansion': false,
        'card_id': 28,
        'card_name': 'Qi Bear',
        'card_name_br': 'Urso do Qi',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Fighter',
        'card_class_br': 'Lutador',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "4+ Each other player with a Fighter in their Party must DISCARD a card.",
        'card_effect_br': '4+ Cada outro jogador com um Lutador em sem grupo deve DESCARTAR uma carta.',
        'card_expansion': false,
        'card_id': 29,
        'card_name': 'Tough Teddy',
        'card_name_br': 'Ursinho Brigão',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Fighter',
        'card_class_br': 'Lutador',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "9+ Trade hands with another player.",
        'card_effect_br': '9+ Troque de mão com outro jogador.',
        'card_expansion': false,
        'card_id': 30,
        'card_name': 'Dodgy Dealer',
        'card_name_br': 'Negociante Duvidoso',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Bard',
        'card_class_br': 'Bardo',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "8+ DRAW a card and play a Hero card from your hand immediately.",
        'card_effect_br': '8+ COMPRE uma carta e jogue uma Carta de Herói da sua mão imediatamente.',
        'card_expansion': false,
        'card_id': 31,
        'card_name': 'Fuzzy Cheeks',
        'card_name_br': 'Bochechas Peludas',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Bard',
        'card_class_br': 'Bardo',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "8+ Each other player must give you a card from their hand.",
        'card_effect_br': '8+ Cada outro jogador deve te dar uma carta da própria mão.',
        'card_expansion': false,
        'card_id': 32,
        'card_name': 'Greedy Cheeks',
        'card_name_br': 'Bochechas Gananciosas',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Bard',
        'card_class_br': 'Bardo',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "7+ Pull a card from another player's hand. If that card is a Hero card, you may play it immediately",
        'card_effect_br': '7+ Pegue uma carta da mão de outro jogador. Se essa carta for uma Carta de Herói, você pode joga-la imediatamente.',
        'card_expansion': false,
        'card_id': 33,
        'card_name': 'Lucky Bucky',
        'card_name_br': 'Bucky Sortuda',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Bard',
        'card_class_br': 'Bardo',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "7+ DRAW a card. If that card is a Hero card, you may play it immediately.",
        'card_effect_br': '7+ COMPRE uma carta. Se essa carta for uma Carta de Herói, você pode joga-la imediamente.',
        'card_expansion': false,
        'card_id': 34,
        'card_name': 'Mellow Dee',
        'card_name_br': 'Soneto',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Bard',
        'card_class_br': 'Bardo',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "2+ Do nothing.",
        'card_effect_br': '2+ Não faça nada.',
        'card_expansion': false,
        'card_id': 35,
        'card_name': 'Napping Nibbles',
        'card_name_br': 'Cochilo Mordiscante',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Bard',
        'card_class_br': 'Bardo',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "7+ DRAW 2 cards.",
        'card_effect_br': '7+ COMPRE 2 cartas.',
        'card_expansion': false,
        'card_id': 36,
        'card_name': 'Peanut',
        'card_name_br': 'Amendoim',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Bard',
        'card_class_br': 'Bardo',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "6+ Choose a player. STEAL a Hero card from that player's Party and move Tipsy Tootie to that player's Party.",
        'card_effect_br': '6+ Escolha outro jogador. ROUBE uma Carta de Herói do grupo deste jogador e mova Dentinhos Embriagados para o grupo deste jogador.',
        'card_expansion': false,
        'card_id': 37,
        'card_name': 'Tipsy Tootie',
        'card_name_br': 'Dentinhos Embriagados',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Bard',
        'card_class_br': 'Bardo',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "9+ Hero cards in your Party cannot be stolen until your next turn.",
        'card_effect_br': '9+ Cartas de Herói no seu grupo não podem ser roubadas até o seu próximo turno.',
        'card_expansion': false,
        'card_id': 38,
        'card_name': 'Calming Voice',
        'card_name_br': 'Voz Calmante',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Guardian',
        'card_class_br': 'Guardião',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "7+ Search the discard pile for a Hero card and add it to your hand.",
        'card_effect_br': '7+ Procure na pilha de descarte por uma Carta de Herói e adicione-a à sua mão.',
        'card_expansion': false,
        'card_id': 39,
        'card_name': 'Guiding Light',
        'card_name_br': 'Luz Guiadora',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Guardian',
        'card_class_br': 'Guardião',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "5+ Return a Cursed Item card equipped to a Hero card in your Party to your hand.",
        'card_effect_br': '5+ Retorne uma Carta de Item Amaldiçoado equipado em um Herói do seu grupo para a sua mão.',
        'card_expansion': false,
        'card_id': 40,
        'card_name': 'Holy Curselifter',
        'card_name_br': 'Quebrador de Maldição Sagrado',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Guardian',
        'card_class_br': 'Guardião',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "8+ Cards you play cannot be challenged for the rest of your turn.",
        'card_effect_br': '8+ Cartas que você jogar não podem ser desafiadas pelo resto do seu turno.',
        'card_expansion': false,
        'card_id': 41,
        'card_name': 'Iron Resolve',
        'card_name_br': 'Determinação de Ferro',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Guardian',
        'card_class_br': 'Guardião',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "8+ Hero cards in your Party cannot be destroyed until your next turn.",
        'card_effect_br': '8+ Cartas de Herói no seu Grupo não podem ser destruidas até o seu próximo turno.',
        'card_expansion': false,
        'card_id': 42,
        'card_name': 'Mighty Blade',
        'card_name_br': 'Lâmina Poderosa',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Guardian',
        'card_class_br': 'Guardião',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "6+ Search the discard pile for a Modifier card and add it to your hand.",
        'card_effect_br': '6+ Procure na pilha de descarte por uma Carta de Modificador e a coloque-a na sua mão.',
        'card_expansion': false,
        'card_id': 43,
        'card_name': 'Radiant Horn',
        'card_name_br': 'Chifre Radiante',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Guardian',
        'card_class_br': 'Guardião',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "9+ +5 to all your rolls until the end of your turn.",
        'card_effect_br': '9+ +5 para todas as suas roladas até o final do seu turno.',
        'card_expansion': false,
        'card_id': 44,
        'card_name': 'Vibrant Glow',
        'card_name_br': 'Brilho Vibrante',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Guardian',
        'card_class_br': 'Guardião',
    },
    {
        'card_edition': 'Base Game',
        'card_edition_br': 'Jogo Base',
        'card_effect': "6+ +3 to all your rolls until the end of your turn.",
        'card_effect_br': '6+ +3 para todas as suas roladas até o final do seu turno.',
        'card_expansion': false,
        'card_id': 45,
        'card_name': 'Wise Shield',
        'card_name_br': 'Escudo Sábio',
        'card_type': 'Hero Card',
        'card_type_br': 'Carta de Herói',
        'game': 'Here To Slay',
        'card_class': 'Guardian',
        'card_class_br': 'Guardião',
    },
]


export default htsCards