export default function getCardImage(cardID:number) {
	switch(cardID) {
		case 1:
			return require('../assets/happy_little_dinosaurs/a_day_at_the_beach.png');;
		case 2:
			return require('../assets/happy_little_dinosaurs/armed_and_dangerous.png');;
		case 3:
			return require('../assets/happy_little_dinosaurs/baddest_hair_day.png');
		case 4:
			return require('../assets/happy_little_dinosaurs/bright_idea.png');
		case 5:
			return require('../assets/happy_little_dinosaurs/casual_afternoon_stroll.png');
		case 6:
			return require('../assets/happy_little_dinosaurs/downpour.png');
		case 7:
			return require('../assets/happy_little_dinosaurs/emergency_ex_it.png');
        case 8:
			return require('../assets/happy_little_dinosaurs/feeling_squirrely.png');
        case 9:
			return require('../assets/happy_little_dinosaurs/fired_up.png');
        case 10:
            return require('../assets/happy_little_dinosaurs/ghosted.png');
        case 11:
            return require('../assets/happy_little_dinosaurs/leaf_me_alone.png');  
        case 12:
            return require('../assets/happy_little_dinosaurs/left_behind_again.png');  
        case 13:
            return require('../assets/happy_little_dinosaurs/lil_cannibal.png');  
        case 14:
            return require('../assets/happy_little_dinosaurs/love_hurts.png');  
        case 15:
            return require('../assets/happy_little_dinosaurs/meteor.png');  
        case 16:
            return require('../assets/happy_little_dinosaurs/ooh_burn.png');  
        case 17:
            return require('../assets/happy_little_dinosaurs/outer_circle.png');  
        case 18:
            return require('../assets/happy_little_dinosaurs/shark_with_legs.png');  
        case 19:
            return require('../assets/happy_little_dinosaurs/spa_day.png');  
        case 20:
            return require('../assets/happy_little_dinosaurs/stomped.png');
        case 21:
            return require('../assets/happy_little_dinosaurs/the_future_is_bleak.png');  
        case 22:
            return require('../assets/happy_little_dinosaurs/the_sad_truth.png');  
        case 23:
            return require('../assets/happy_little_dinosaurs/this_feels_personal.png');  
        case 24:
            return require('../assets/happy_little_dinosaurs/trapped.png');  
        case 25:
            return require('../assets/happy_little_dinosaurs/uncommon_cold.png');  
        case 26:
            return require('../assets/happy_little_dinosaurs/bonehead.png');  
        case 27:
            return require('../assets/happy_little_dinosaurs/bow_and_dino.png');
        case 28:
            return require('../assets/happy_little_dinosaurs/cool_stick.png');  
        case 29:
            return require('../assets/happy_little_dinosaurs/delicious_smoothie.png');  
        case 30:
            return require('../assets/happy_little_dinosaurs/dino_grabber.png');
        case 31:
            return require('../assets/happy_little_dinosaurs/fire_spray.png');
        case 32:
            return require('../assets/happy_little_dinosaurs/flaming_chainsaw.png');
        case 33:
            return require('../assets/happy_little_dinosaurs/grappling_snake.png');
        case 34:
            return require('../assets/happy_little_dinosaurs/grave_maker.png');
        case 35:
            return require('../assets/happy_little_dinosaurs/handy_pan.png');
        case 36:
            return require('../assets/happy_little_dinosaurs/run_home_bat.png');
        case 37:
            return require('../assets/happy_little_dinosaurs/hungry_plant.png');
        case 38:
            return require('../assets/happy_little_dinosaurs/iced_ptea.png');
        case 39:
            return require('../assets/happy_little_dinosaurs/meteor_cannon.png');
        case 40:
            return require('../assets/happy_little_dinosaurs/mouth_trap.png');
        case 41:
            return require('../assets/happy_little_dinosaurs/pet_rock.png');
        case 42:
            return require('../assets/happy_little_dinosaurs/special_star_fruit.png');
        case 43:
            return require('../assets/happy_little_dinosaurs/sting_stabber.png');
        case 44:
            return require('../assets/happy_little_dinosaurs/treenoculars.png');
        case 45:
            return require('../assets/happy_little_dinosaurs/disaster_insurance.png');
        case 46:
            return require('../assets/happy_little_dinosaurs/disaster_redirect.png');
        case 47:
            return require('../assets/happy_little_dinosaurs/score_booster.png');
        case 48:
            return require('../assets/happy_little_dinosaurs/score_inversion.png');
        case 49:
            return require('../assets/happy_little_dinosaurs/score_sapper.png');

}}